esphome:
  name: pylon-protocol-emulator
  friendly_name: pylon-protocol-emulator

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GqFsrbX7ZG8o5bZ5Q8o9jnMg1HT3IX//Q0jCulYl8rQ="

ota:
  - platform: esphome
    password: "451373e86437476c7be4b75efbae484e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pylon-Protocol-Emulator"
    password: "n03lnKCQ7m1I"

captive_portal:
    