esphome:
  name: esp32-c3
  friendly_name: ESP32-C3
  platform: ESP32
  board: esp32-c3-devkitm-1

  on_boot:
    then:
      - light.turn_on:
          id: backlight
          brightness: 65%

external_components:
  - source: github://ParineetVernekar/esphome@pr3625fix
    components: [gc9a01]

wifi:
  ssid: ff
  password: fffdsfsdfsdfsd

api:
logger:

spi:
  mosi_pin: GPIO10
  clk_pin: GPIO7

light:
  - platform: monochromatic
    id: backlight
    name: "Backlight"
    output: pwm_output

output:
  - platform: ledc
    id: pwm_output
    pin: GPIO3

##################
# Sensors from HA
##################
time:
  - platform: sntp
    id: my_time
    timezone: America/Phoenix

sensor:
  - platform: homeassistant
    id: outside_temp_dht22
    entity_id: sensor.dht22_temp

  - platform: homeassistant
    id: openweather_temp
    entity_id: sensor.openweathermap_temp_rounded

  - platform: homeassistant
    id: spa_temp
    entity_id: sensor.pool_temp

binary_sensor:
  - platform: homeassistant
    id: office_motion
    entity_id: binary_sensor.office_motion_sensor

  - platform: homeassistant
    id: spa_heater
    entity_id: switch.pool_spa
  
text_sensor:
  - platform: homeassistant
    id: weather
    entity_id: weather.openweathermap
    internal: true

  - platform: homeassistant
    name: Readable_time
    entity_id: sensor.12h_time
    id: readable_ha_time

color:
  - id: yellow
    hex: FFC300
  - id: light_gray
    hex: DEDEDE

display:
  - platform: gc9a01
    id: round
    reset_pin: GPIO4
    cs_pin: GPIO6
    dc_pin: GPIO5
    lambda: //