esphome:
  name: test
  friendly_name: Test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "iCc+2dea+uF9uh1hV5DE3/GEqkIDGnQXJrKjVZRrBVE="

ota:
  password: "cd7ad23c86bcb01ff25afd17ba4dc623"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "6uaUhzywZP57"

captive_portal:
    