logger:

api:

ota:
  id: my_ota
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  fast_connect: true
  ap:
    ssid: ${device_name}
    password: !secret wifi_ap_password

captive_portal:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Kiev

sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 120s
  - platform: uptime
    id: uptime_seconds
    name: "${device_name} uptime seconds"
    update_interval: 120s
