stages:
  - deploy

.esphome-deploy: &esphome-deploy
  stage: deploy
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  image:
    name: esphome/esphome:latest
    entrypoint: [""]
  script:
    - |
      for file in $(find \
        ./ \
        -type f \
        -name "*.yaml"\
        -not -name "secrets.yaml"
        ); do
        esphome $file compile
      done
  tags:
    - hass


esphome-latest:
  <<: *esphome-deploy
  image:
    name: esphome/esphome:latest
  entrypoint: [""]
