stages:
  - deploy

.esphome-deploy: &esphome-deploy
  stage: deploy
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  image:
    name: esphome/esphome:latest
    entrypoint: [""]
  retry: 2

esphome-latest:
  <<: *esphome-deploy
  image:
    name: esphome/esphome:latest
    entrypoint: [""]
  script: echo '0'
