esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  includes:
    - includes/HaierV2.h

logger:
  level: DEBUG
  baud_rate: 0

uart:
  id: haier_uart
  tx_pin: D6
  rx_pin: D5
  baud_rate: 9600
  rx_buffer_size: 64

status_led:
  pin:
    number: GPIO2
    inverted: yes

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Kiev 

climate:
  - platform: custom
    lambda: |-
      auto uart = id(haier_uart);
      auto haier = new Haier(uart);
      App.register_component(haier);
      return {haier};
    climates:
      - name: ${climate_name}

packages:
  device_common: !include .device_common.yaml
