esphome:
  name: ${device_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  device_common: !include .device_common.yaml

logger:
  level: DEBUG
  baud_rate: 115200

status_led:
  pin:
    number: GPIO2
    inverted: yes

uart:
  id: uart_0
  rx_pin: GPIO18
  tx_pin: GPIO19
  baud_rate: 115200
  debug:
    direction: BOTH
    dummy_receiver: false
    sequence:
      - lambda: |-
          UARTDebug::log_hex(direction, bytes, ':');

debug:
  update_interval: 5s

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

modbus:
  - id: modbus0
    uart_id: uart_0
    send_wait_time: 200ms

web_server:
  version: 2