globals:
  - id: relay_state
    type: boolean
    restore_value: true
    initial_value: "true"

esphome:
  esp8266_restore_from_flash: true
  on_boot:
    priority: 600
    then:
      - if:
          condition:
            - lambda: 'return id(relay_state);'
          then:
            - if:
                condition:
                  - lambda: 'return system_get_rst_info()->reason == 0;'
                then:
                  - delay: ${delay_time}
            - switch.turn_on: relay_phy

binary_sensor:
  - platform: gpio
    pin:
      number: ${button_pin}
      mode: INPUT_PULLUP
      inverted: true
    id: relay_button
    internal: true
    on_press:
      - switch.toggle: relay_phy

switch:
  - platform: gpio
    id: relay_phy
    name: "${device_name} relay"
    pin: ${relay_pin}
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - lambda: id(relay_state) = true;
    on_turn_off:
      - lambda: |-
          static bool initial = true;
          if (initial) {
            initial = false;
          } else {
            id(relay_state) = false;
          }
