substitutions:
  device_name: "ajax-armed-sense"

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

sensor:
  - platform: pulse_meter
    pin:
      number: D7
      inverted: true
    id: ajax_homesiren_led_pulses
    name: "AJAX HomeSiren LED Pulses"
    timeout: 5s
    internal_filter_mode: EDGE
    internal: true

binary_sensor:
  - platform: template
    name: "AJAX armed state"
    icon: "mdi:shield"
    device_class: ''
    lambda: >-
      return id(ajax_homesiren_led_pulses).state > 0;
