substitutions:
  device_name: battery-status-display
  device_name_underscore: battery_status_display

globals:
  - id: voltage
    type: float
    initial_value: '0.0'
  - id: soc
    type: float
    initial_value: '0.0'
  - id: power
    type: float
    initial_value: '0.0'
  - id: min_cell_voltage
    type: float
    initial_value: '0.0'
  - id: max_cell_voltage
    type: float
    initial_value: '0.0'
  - id: min_cell_temp
    type: float
    initial_value: '0.0'
  - id: max_cell_temp
    type: float
    initial_value: '0.0'
  - id: mos_temp
    type: float
    initial_value: '0.0'

esphome:
  name: ${device_name}

esp32:
  framework: 
    type: arduino
    version: recommended
  board: esp32-c3-devkitm-1

external_components:
  - source: github://syssi/esphome-jk-bms@main
    components: [jk_bms_display]

packages:
  device_common: !include .device_common.yaml
  jkbms_disp_port: !include 
    file: battery-status-display/jkbms-display-port.yaml
    vars:
      rx_pin: GPIO20
  lvgl-ui: !include battery-status-display/lvgl-ui.yaml

logger:
  baud_rate: 0

spi:
  mosi_pin: GPIO7
  clk_pin: GPIO6

i2c:
  sda: GPIO4
  scl: GPIO5

output:
  - platform: ledc
    pin: GPIO3
    id: gpio_3_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

display:
  - platform: ili9xxx
    id: watchface
    model: GC9A01A
    cs_pin: GPIO10
    dc_pin: GPIO2
    data_rate: 80MHz
    pixel_mode: 16bit
    dimensions:
      width: 240
      height: 240
    update_interval: never
    invert_colors: false
    auto_clear_enabled: false

touchscreen:
  id: cst816d
  platform: cst816
  interrupt_pin: GPIO0
  reset_pin: GPIO1
  on_release:
    - script.execute: lvgl_resume

interval:
  - interval: 1s
    id: update_labels_interval
    then:
      script.execute: lvgl_update_values

script:
  - id: lvgl_update_values
    mode: single
    then:
      - lvgl.label.update:
          id: cap_label
          text:
            format: "%.0f%%"
            args: ['id(soc)']
      - lvgl.label.update:
          id: soc_label
          text:
            format: "%.0fW"
            args: ['id(power)']

debug:

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  - platform: internal_temperature
    name: ESP32 Internal temperature
    entity_category: diagnostic