substitutions:
  device_name: battery-controller
  pace_tx: GPIO10
  pace_rx: GPIO11
  pace_fctl: GPIO12
  jkbms_tx: GPIO42
  jkbms_rx: GPIO1
  jkbms_fctl: GPIO2

packages:
  device_common: !include .device_common.yaml
  lvgl-ui: !include battery-controller/lvgl-ui.yaml
  jkbms_modbus: !include 
    file: battery-controller/jkbms-modbus.yaml
    vars:
      tx_pin: ${jkbms_tx}
      rx_pin: ${jkbms_rx}
      fctl_pin: ${jkbms_fctl}
  pace-bms: !include
    file: battery-controller/pace-bms-emulator.yaml
    vars:
      tx_pin: ${pace_tx}
      rx_pin: ${pace_rx}
      fctl_pin: ${pace_fctl}
  # jkbms_gps: !include 
  #   file: battery-controller/jkbms-gps.yaml
  #   vars:
  #     jkbms_tx: ${jkbms_tx}
  #     jkbms_rx: ${jkbms_rx}
  # jkbms_ble: !include 
  #   file: battery-controller/jkbms-ble.yaml
  #   vars:
  #     mac_address: "C8:47:80:1D:6A:49"
  #     protocol_version: JK02_32S
  # jkbms-faker: !include battery-controller/jkbms-faker.yaml
  # powmr: !include
  #   file: battery-controller/powmr.yaml
  #   vars:
  #     inverter_tx: GPIO43
  #     inverter_rx: GPIO44
  # pace-bms: !include
  #   file: battery-controller/pace-bms-faker.yaml
  #   vars:
  #     modbus_tx:   ${modbus_tx}
  #     modbus_rx:   ${modbus_rx}

globals:
  - id: inverter_on
    type: bool
    initial_value: 'false'
  - id: current_tile_num
    type: uint8_t
    initial_value: '0'
  - id: is_automatic_tile_change
    type: bool
    initial_value: 'false'
  - id: clr_num
    type: uint8_t
    initial_value: '0'

wifi:
  on_connect:
    - script.execute:
        id: lvgl_update_status_icon
        name: api_connection
        is_on: true
  on_disconnect:
    - script.execute:
        id: lvgl_update_status_icon
        name: api_connection
        is_on: false

esphome:
  name: battery-controller
  friendly_name: battery-controller
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      # CONFIG_ESP_MAIN_TASK_STACK_SIZE: "65535"

psram:
  mode: quad
  speed: 80MHZ

external_components:
  - source: github://pr#6537
    components: [ io_bus, i80, spi, ili9xxx ]
  - source: github://syssi/esphome-jk-bms@main

logger:
  baud_rate: 0
  level: WARN
  # logs:
  #   sensor: ERROR
  #   text_sensor: ERROR
  #   modbus: ERROR
  #   lvgl: ERROR
  #   interval: ERROR
  #   component: ERROR
  #   modbus_controller: DEBUG
  #   uart: DEBUG
  #   component: ERROR
  #   jk_bms: ERROR

debug:

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"
  - platform: internal_temperature
    name: ESP32 Internal temperature
    entity_category: diagnostic

i2c:
  sda: GPIO6
  scl: GPIO5
  id: touch_i2c

touchscreen:
  - platform: ft63x6
    id: touch
    interrupt_pin: GPIO7
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: true
    on_release:
      - script.execute: lvgl_resume

output:
  - platform: ledc
    id: backlight_pwm
    pin:
      number: GPIO45
      ignore_strapping_warning: true

light:
  - platform: monochromatic
    id: backlight
    output: backlight_pwm
    restore_mode: ALWAYS_ON

i80:
  - id: i80bus
    dc_pin: 
      number: GPIO0
      ignore_strapping_warning: true
    wr_pin: GPIO47
    data_pins:
      - GPIO9
      - number: GPIO46
        ignore_strapping_warning: true
      - number: GPIO3
        ignore_strapping_warning: true
      - GPIO8
      - GPIO18
      - GPIO17
      - GPIO16
      - GPIO15

display:
  - platform: ili9xxx
    model: ST7796
    bus_type: i80
    reset_pin: GPIO4
    pixel_mode: 16bit
    color_order: bgr
    invert_colors: true
    dimensions:
      width: 480
      height: 320
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: true
    auto_clear_enabled: false

button:
  - id: turn_on_screen
    name: ${device_name} turn on screen
    platform: template
    on_press:
      - script.execute:
          id: lvgl_resume
