substitutions:
  device_name: battery-controller

packages:
  device_common: !include .device_common.yaml

api:
  on_client_connected:
    lvgl.widget.update:
      id: api_connection
      text_color: on_icon_color

esphome:
  name: battery-controller
  friendly_name: battery-controller
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: quad
  speed: 80MHZ

external_components:
  - source: github://pr#6537
    components: [ io_bus, i80, spi, ili9xxx ]
  - source: github://clydebarrow/esphome@lvgl
    components: [ lvgl ]

logger:

debug:

# uart:
  # - id: bms_uart
  #   tx_pin: GPIO10
  #   rx_pin: GPIO11
  #   baud_rate: 115200

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"

i2c:
  sda: GPIO6
  scl: GPIO5
  id: touch_i2c

touchscreen:
  - platform: ft63x6
    id: touch
    interrupt_pin: GPIO7
    transform:
      swap_xy: true
      mirror_x: true
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume
            - lvgl.widget.show: header
            - lvgl.page.show: main_page
            - light.turn_on: backlight
    on_touch:
      - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
          );

output:
  - platform: ledc
    id: backlight_pwm
    pin:
      number: GPIO45
      ignore_strapping_warning: true

light:
  - platform: monochromatic
    id: backlight
    output: backlight_pwm
    restore_mode: ALWAYS_ON

font:
  - file: battery-controller/SquareDotMatrix.ttf
    id: font_soc
    bpp: 4
    size: 36
    glyphs: ['0','1','2','3','4','5','6','7','8','9','%',' ']

color:
  - id: color_red
    red: 100%
  - id: color_green
    green: 100%
  - id: off_icon_color
    hex: FF4F00
  - id: on_icon_color
    hex: 58D900

i80:
  - id: i80bus
    dc_pin: 
      number: GPIO0
      ignore_strapping_warning: true
    wr_pin: GPIO47
    data_pins:
      - GPIO9
      - number: GPIO46
        ignore_strapping_warning: true
      - number: GPIO3
        ignore_strapping_warning: true
      - GPIO8
      - GPIO18
      - GPIO17
      - GPIO16
      - GPIO15

display:
  - platform: ili9xxx
    model: ST7796
    bus_type: i80
    reset_pin: GPIO4
    pixel_mode: 16bit
    color_order: bgr
    invert_colors: true
    dimensions:
      width: 480
      height: 320
    transform:
      swap_xy: true
    auto_clear_enabled: false

number:
  - platform: template
    name: Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box
  - platform: template
    name: SOC test
    optimistic: true
    initial_value: 42
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1
    mode: slider
    on_value:
      then:
        - lvgl.arc.update:
            id: soc_arc
            value: !lambda return x;
            indicator:
              arc_color: !lambda |-
                auto color = id(color_red).gradient(id(color_green), x * 2.55);
                return lv_color_make (color.red, color.green, color.blue);
        - lvgl.label.update:
            id: soc_label
            text:
              format: "%d%%"
              args: (int)x

interval:
  - interval: 1sec
    startup_delay: 5sec
    then:
      - if:
          condition:
            not: lvgl.is_paused
          then:
            lvgl.label.update:
              id: header_time
              text: !lambda |-
                if (!id(sntp_time->now()).is_valid()) {
                  return "--:--:--";
                }
                static char time_buf[17];
                auto time = id(sntp_time).now();
                snprintf(time_buf, sizeof(time_buf), "%02d:%02d:%02d", time.hour, time.minute, time.second);
                return time_buf;
  - interval: 1min
    startup_delay: 5sec
    then:
      - if:
          condition:
            not: lvgl.is_paused
          then:
            lvgl.label.update:
              id: header_date
              text: !lambda |-
                static const char* const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
                static char date_buf[16];
                auto now = id(sntp_time).now();
                snprintf(date_buf, sizeof(date_buf), "%s %02d, %d", mon_names[now.month-1], now.day_of_month, now.year);
                return date_buf;

lvgl:
  log_level: WARN
  color_depth: 16
  bg_color: 0x0F0F0F
  text_font: unscii_8
  align: center
  touchscreens:
    - touchscreen_id: touch
  top_layer:
    widgets:
      - obj:
          id: header
          bg_color: 0x14191E
          height: 20
          width: 100%
          radius: 0
          x: 0
          y: 0
          border_width: 0
          scrollable: false
          align: TOP_MID
          pad_right: 0
          widgets:
            - label:
                id: header_date
                align: LEFT_MID
                width: SIZE_CONTENT
                height: SIZE_CONTENT
                text: " "
                text_color: 0xFFFFFF
                text_font: montserrat_14
            - obj:
                bg_opa: 0
                border_opa: 0
                radius: 0
                width: 160
                height: 20
                pad_all: 0
                align: RIGHT_MID
                scrollable: false
                layout:
                  type: FLEX
                  flex_flow: ROW
                  flex_align_main: END
                  flex_align_cross: CENTER
                  flex_align_track: CENTER
                widgets:
                  - label:
                      id: header_time
                      width: SIZE_CONTENT
                      height: SIZE_CONTENT
                      text: "--:--:--"
                      text_color: 0xFFFFFF
                      text_font: montserrat_14
                  - label:
                      id: api_connection
                      width: 16
                      height: 16
                      text: "\uF1EB"
                      text_color: off_icon_color
                      text_font: montserrat_16
                  - label:
                      id: bms_connection
                      width: 16
                      height: 16
                      text: "\uF008"
                      text_color: off_icon_color
                      text_font: montserrat_16
                  - label:
                      id: inverter_connection
                      width: 16
                      height: 16
                      text: "\uF0E7"
                      text_color: off_icon_color
                      text_font: montserrat_16

  pages:
    # - <<: !include battery-controller/main-page.lvgl.yaml
    # - <<: !include battery-controller/voltages-page.lvgl.yaml
    - id: main_page
      bg_color: 0x606672
      bg_grad_color: 0x33363E
      bg_grad_dir: VER
      bg_dither_mode: ERR_DIFF
      scrollable: false
      widgets:
        # SOC gauge
        - obj:
            width: 240
            height: 240
            x: 40
            y: 40
            scrollable: false
            bg_color: 0xFFFFFF
            bg_opa: 0
            border_width: 0
            widgets:
              - arc:
                  id: soc_arc
                  width: 210
                  height: 210
                  align: CENTER
                  min_value: 0
                  max_value: 100
                  value: 42
                  radius: 210
                  bg_color: 0x1E232D
                  bg_opa: 1
                  pad_left: 5
                  pad_right: 5
                  pad_top: 5
                  pad_bottom: 5
                  arc_color: 0x0F1215
                  indicator:
                    arc_color: 0x00FF00
                    width: 12
                  knob:
                    bg_opa: 0
              - obj:
                  width: 168
                  height: 168
                  align: CENTER
                  clickable: false
                  scrollable: false
                  radius: 168
                  bg_color: 0x646464
                  bg_grad_color: 0x3C414B
                  bg_grad_dir: VER
                  bg_opa: 1
                  border_color: 0x2D323C
                  border_width: 1
                  shadow_color: 0x050A0F
                  shadow_width: 40
                  shadow_spread: 0
                  shadow_ofs_x: 0
                  shadow_ofs_y: 15
                  widgets:
                    - obj:
                        width: 120
                        height: 120
                        align: CENTER
                        clickable: false
                        scrollable: false
                        radius: 120
                        bg_color: 0x0C191E
                        bg_grad_color: 0x191C26
                        bg_grad_dir: VER
                        bg_opa: 1
                        border_color: 0x5A646E
                        widgets:
                          - label:
                              id: soc_label
                              width: SIZE_CONTENT
                              height: SIZE_CONTENT
                              x: 0
                              y: 0
                              align: CENTER
                              text_color: 0xFFFFFF
                              text: '100%'
                              text_font: font_soc
        # Status led and label
        - obj:
            scrollable: false
            x: 0
            y: 280
            bg_opa: 0
            border_opa: 0
            width: 280
            height: 40
            widgets:
              - led:
                  id: charge_led
                  color: color_red
                  align: LEFT_MID
                  brightness: 100%
                  width: 10
                  height: 10
              - label:
                  id: charge_label
                  width: SIZE_CONTENT
                  height: 20
                  align_to:
                    id: charge_led
                    align: OUT_RIGHT_MID
                    y: 2
                    x: 10
                  text: 'Discharging'
                  text_color: 0xD2CDC8
                  text_align: LEFT
                  text_font: montserrat_14
        # Right panel
        - obj:
            x: 320
            y: 20
            height: 300
            width: 160
            bg_color: 0x202831
            bg_grad_color: 0x101215
            bg_dither_mode: ERR_DIFF
            bg_grad_dir: VER
            radius: 0
            border_opa: 0
            pad_all: 0
            scrollable: false
            widgets:
              - obj:
                  bg_opa: 0
                  border_opa: 0
                  align: CENTER
                  radius: 0
                  width: 100%
                  height: SIZE_CONTENT
                  scrollable: false
                  layout:
                    type: FLEX
                    flex_flow: COLUMN
                    flex_align_main: SPACE_AROUND
                    flex_align_track: START
                    flex_align_cross: SPACE_AROUND
                  pad_row: 0
                  widgets:
                    - obj:
                        width: 100%
                        height: SIZE_CONTENT
                        bg_opa: 0
                        border_opa: 0
                        radius: 0
                        align: CENTER
                        scrollable: false
                        widgets:
                          - label:
                              id: voltage_label
                              width: SIZE_CONTENT
                              height: SIZE_CONTENT
                              text_color: 0x58D900
                              text_font: montserrat_26
                              text_align: RIGHT
                              text: '56.5'
                          - label:
                              width: SIZE_CONTENT
                              height: SIZE_CONTENT
                              text_color: 0x58D900
                              text_font: montserrat_16
                              text_align: RIGHT
                              text: 'V'
                              align_to:
                                id: voltage_label
                                align: OUT_RIGHT_TOP
                                x: 3
                    - obj:
                        width: 100%
                        height: SIZE_CONTENT
                        bg_opa: 0
                        border_opa: 0
                        radius: 0
                        align: CENTER
                        scrollable: false
                        widgets:
                          - label:
                              id: current_label
                              width: SIZE_CONTENT
                              height: SIZE_CONTENT
                              text_color: 0x58D900
                              text_font: montserrat_26
                              text_align: RIGHT
                              text: '299.99'
                          - label:
                              width: SIZE_CONTENT
                              height: SIZE_CONTENT
                              text_color: 0x58D900
                              text_font: montserrat_16
                              text_align: RIGHT
                              text: 'A'
                              align_to:
                                id: current_label
                                align: OUT_RIGHT_TOP
                                x: 3
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: voltage, l_capt: Voltage } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: current, l_capt: Current } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: ccap, l_capt: Cycle capacity } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: ccnt, l_capt: Cycle count } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: avg_cell_v, l_capt: Avg. cell voltage } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: delte_cell_v, l_capt: Delta cell voltage } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: t1, l_capt: Temp 1 } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: t2, l_capt: Temp 2 } }
                    # - <<: !include { file: battery-controller/stat-label-group.yaml, vars: { l_name: tmos, l_capt: MOS Temp } }
                    # Right panel footer
                    - obj:
                        bg_opa: 0
                        hidden: true
                        border_opa: 0
                        width: 100%
                        height: SIZE_CONTENT
                        widgets:
                          - label:
                              text: "\uF053"
                              text_color: 0xFFFFFF
                              text_font: montserrat_18
                              text_align: LEFT
                              # ignore_layout: true
                              width: 50%
                              height: 25
                              # align: CENTER
                              # x: 130
                              # y: 5
                              on_click:
                                - lvgl.page.show: details_page
                          - label:
                              text: "\uF054"
                              text_color: 0xFFFFFF
                              text_font: montserrat_18
                              text_align: RIGHT
                              width: 50%
                              height: 25
                              # align: CENTER

    - id: details_page
      bg_color: 0x202831
      bg_grad_color: 0x101215
      bg_grad_dir: VER
      bg_dither_mode: ERR_DIFF
    - id: burnout_protection_page
      bg_color: 0x000000
      bg_opa: 1
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - light.turn_off: backlight
      - lvgl.widget.hide: header
      - lvgl.page.show: burnout_protection_page
      - delay: 1s
      - lvgl.pause
