substitutions:
  device_name: battery-controller

packages:
  device_common: !include .device_common.yaml

globals:
  - id: inverter_on
    type: bool
    restore_value: false
    initial_value: 'false'
  - id: bms_on
    type: bool
    restore_value: false
    initial_value: 'false'
  - id: is_on
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: display_lock
    type: bool
    restore_value: false
    initial_value: 'false'

api:
  on_client_connected:
    lvgl.widget.update:
      id: api_connection
      text_color: on_color

esphome:
  name: battery-controller
  friendly_name: battery-controller
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: quad
  speed: 80MHZ

external_components:
  - source: github://pr#6537
    components: [ io_bus, i80, spi, ili9xxx ]
  - source: github://clydebarrow/esphome@lvgl
    components: [ lvgl ]

logger:

debug:

uart:
  - id: bms_uart
    tx_pin: GPIO10
    rx_pin: GPIO11
    baud_rate: 115200
  - id: inverter_uart
    tx_pin: GPIO42
    rx_pin: GPIO1
    baud_rate: 9600

modbus:
  - id: inverter_modbus
    uart_id: inverter_uart
    flow_control_pin: GPIO2

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"

i2c:
  sda: GPIO6
  scl: GPIO5
  id: touch_i2c

touchscreen:
  - platform: ft63x6
    id: touch
    interrupt_pin: GPIO7
    transform:
      swap_xy: true
      mirror_x: true
    on_release:
      - script.execute: lvgl_resume

output:
  - platform: ledc
    id: backlight_pwm
    pin:
      number: GPIO45
      ignore_strapping_warning: true

light:
  - platform: monochromatic
    id: backlight
    output: backlight_pwm
    restore_mode: ALWAYS_ON

font:
  - file: battery-controller/SquareDotMatrix.ttf
    id: gauge_font
    bpp: 4
    size: 36
    glyphs: ['0','1','2','3','4','5','6','7','8','9','%',' ']

color:
  - id: color_red
    red: 100%
  - id: color_green
    green: 100%
  - id: off_color
    hex: FF4F00
  - id: on_color
    hex: 58D900

i80:
  - id: i80bus
    dc_pin: 
      number: GPIO0
      ignore_strapping_warning: true
    wr_pin: GPIO47
    data_pins:
      - GPIO9
      - number: GPIO46
        ignore_strapping_warning: true
      - number: GPIO3
        ignore_strapping_warning: true
      - GPIO8
      - GPIO18
      - GPIO17
      - GPIO16
      - GPIO15

display:
  - platform: ili9xxx
    model: ST7796
    bus_type: i80
    reset_pin: GPIO4
    pixel_mode: 16bit
    color_order: bgr
    invert_colors: true
    dimensions:
      width: 480
      height: 320
    transform:
      swap_xy: true
    auto_clear_enabled: false

number:
  - platform: template
    name: Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box
  - platform: template
    name: SOC test
    optimistic: true
    initial_value: 42
    restore_value: true
    min_value: 0
    max_value: 100
    step: 1
    mode: slider
    on_value:
      then:
        - script.execute:
            id: lvgl_update_soc
            soc: !lambda return x;

interval:
  - interval: 1sec
    startup_delay: 5sec
    then:
      - script.execute: lvgl_update_time
  - interval: 1min
    startup_delay: 5sec
    then:
      - script.execute: lvgl_update_date

lvgl:
  log_level: WARN
  color_depth: 16
  bg_color: 0x0F0F0F
  text_font: unscii_8
  align: center
  touchscreens:
    - touchscreen_id: touch
  top_layer:
    widgets:
      - obj:
          id: header
          bg_color: 0x14191E
          height: 20
          width: 100%
          radius: 0
          x: 0
          y: 0
          border_width: 0
          scrollable: false
          align: TOP_MID
          pad_right: 0
          widgets:
            - label:
                id: header_date
                align: LEFT_MID
                width: SIZE_CONTENT
                height: SIZE_CONTENT
                text: " "
                text_color: 0xFFFFFF
                text_font: montserrat_14
            - obj:
                bg_opa: 0
                border_opa: 0
                radius: 0
                width: 160
                height: 20
                pad_all: 0
                align: RIGHT_MID
                scrollable: false
                layout:
                  type: FLEX
                  flex_flow: ROW
                  flex_align_main: END
                  flex_align_cross: CENTER
                  flex_align_track: CENTER
                widgets:
                  - label:
                      id: header_time
                      width: SIZE_CONTENT
                      height: SIZE_CONTENT
                      text: "--:--:--"
                      text_color: 0xFFFFFF
                      text_font: montserrat_14
                  - label:
                      id: api_connection
                      width: 16
                      height: 16
                      text: "\uF1EB"
                      text_color: off_color
                      text_font: montserrat_16
                  - label:
                      id: bms_connection
                      width: 16
                      height: 16
                      text: "\uF008"
                      text_color: off_color
                      text_font: montserrat_16
                  - label:
                      id: inverter_connection
                      width: 16
                      height: 16
                      text: "\uF0E7"
                      text_color: off_color
                      text_font: montserrat_16

  pages:
    # Main page
    - id: main_page
      bg_color: 0x606672
      bg_grad_color: 0x33363E
      bg_grad_dir: VER
      bg_dither_mode: ORDERED
      scrollable: false
      widgets:
        # SOC gauge
        - <<: !include { file: battery-controller/lvgl-gauge.yaml, vars: { g_name: soc } }
        # Status led and label
        - obj:
            scrollable: false
            x: 0
            y: 280
            bg_opa: 0
            border_opa: 0
            width: 280
            height: 40
            widgets:
              - led:
                  id: status_led
                  color: off_color
                  align: LEFT_MID
                  brightness: 100%
                  width: 10
                  height: 10
              - label:
                  id: status_label
                  width: SIZE_CONTENT
                  height: 20
                  align_to:
                    id: status_led
                    align: OUT_RIGHT_MID
                    y: 2
                    x: 10
                  text: 'Off'
                  text_color: 0xD2CDC8
                  text_align: LEFT
                  text_font: montserrat_14
        # Right panel
        - tileview:
            x: 320
            y: 20
            height: 300
            width: 160
            tiles:
              - row: 0
                column: 0
                dir: [ RIGHT ]
                widgets:
                  - obj:
                      <<: !include battery-controller/lvgl-tile-container.yaml
                      widgets:
                        - <<: !include { file: battery-controller/lvgl-label-group-big.yaml, vars: { l_name: voltage,  l_capt: Voltage,  l_unit: V  } }
                        - <<: !include { file: battery-controller/lvgl-label-group-big.yaml, vars: { l_name: current,  l_capt: Currrent, l_unit: A  } }
                        - <<: !include { file: battery-controller/lvgl-label-group-big.yaml, vars: { l_name: power,    l_capt: Power,    l_unit: W  } }
                        - <<: !include { file: battery-controller/lvgl-label-group-big.yaml, vars: { l_name: capacity, l_capt: Capacity, l_unit: Ah } }
              - row: 0
                column: 1
                dir: [ LEFT, RIGHT ]
                widgets:
                  - obj:
                      <<: !include battery-controller/lvgl-tile-container.yaml
                      widgets:
                        - <<: !include { file: battery-controller/lvgl-label-group-big.yaml, vars: { l_name: t1,   l_capt: Temp 1,   l_unit: C } }
                        - <<: !include { file: battery-controller/lvgl-label-group-big.yaml, vars: { l_name: t2,   l_capt: Temp 1,   l_unit: C } }
                        - <<: !include { file: battery-controller/lvgl-label-group-big.yaml, vars: { l_name: tmos, l_capt: MOS Temp, l_unit: C } }
              - row: 0
                column: 2
                dir: [ LEFT, RIGHT ]
                widgets:
                  - obj:
                      <<: !include battery-controller/lvgl-tile-container.yaml
                      widgets:
                        - <<: !include { file: battery-controller/lvgl-switch-group.yaml, vars: { sw_name: charge,    sw_capt: Charge } }
                        - <<: !include { file: battery-controller/lvgl-switch-group.yaml, vars: { sw_name: discharge, sw_capt: Discharge } }
                        - <<: !include { file: battery-controller/lvgl-switch-group.yaml, vars: { sw_name: balance,   sw_capt: Balance } }
              - row: 0
                column: 3
                dir: [ LEFT, RIGHT ]
                widgets:
                  - obj:
                      <<: !include battery-controller/lvgl-tile-container.yaml
                      widgets:
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell1voltage,  l_capt: Cell 1,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell2voltage,  l_capt: Cell 2,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell3voltage,  l_capt: Cell 3,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell4voltage,  l_capt: Cell 4,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell5voltage,  l_capt: Cell 5,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell6voltage,  l_capt: Cell 6,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell7voltage,  l_capt: Cell 7,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell8voltage,  l_capt: Cell 8,  l_unit: V } }
              - row: 0
                column: 4
                dir: [ LEFT ]
                widgets:
                  - obj:
                      <<: !include battery-controller/lvgl-tile-container.yaml
                      widgets:
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell9voltage,  l_capt: Cell 9,  l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell10voltage, l_capt: Cell 10, l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell11voltage, l_capt: Cell 11, l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell12voltage, l_capt: Cell 12, l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell13voltage, l_capt: Cell 13, l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell14voltage, l_capt: Cell 14, l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell15voltage, l_capt: Cell 15, l_unit: V } }
                        - <<: !include { file: battery-controller/lvgl-label-group.yaml, vars: { l_name: cell16voltage, l_capt: Cell 16, l_unit: V } }
    # Blank page
    - id: blank_page
      bg_color: 0x000000
      bg_opa: 1
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - script.execute: lvgl_pause

switch:
  - id: precharge_relay
    platform: gpio
    pin: GPIO21
    internal: true
  - id: contactor_relay
    platform: gpio
    pin: GPIO14
    internal: true
  - id: on_switch
    platform: template
    restore_mode: DISABLED
    lambda: return id(is_on);
    turn_on_action:
      - script.execute:
          id: turn_on
          precharge: !lambda |-
            return !id(inverter_on);
      - globals.set:
          id: is_on
          value: 'true'
    turn_off_action:
      - script.execute: turn_off
      - globals.set:
          id: is_on
          value: 'false'

binary_sensor:
  - id: precharge_sensor
    platform: gpio
    pin:
      number: GPIO13
      inverted: true
    internal: true
  - id: precharge_button
    platform: gpio
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
      inverted: true
    internal: true
    filters:
      - delayed_on: 20ms
      - delayed_off: 20ms
    on_press:
      - script.execute: lvgl_resume
    on_multi_click:
      - timing:
          - ON FOR AT LEAST 2S
        then:
          - switch.toggle: on_switch

script:
  - id: lvgl_update_time
    then:
      - if:
          condition:
            not: lvgl.is_paused
          then:
            lvgl.label.update:
              id: header_time
              text: !lambda |-
                if (!id(sntp_time->now()).is_valid()) {
                  return "--:--:--";
                }
                static char time_buf[17];
                auto time = id(sntp_time).now();
                snprintf(time_buf, sizeof(time_buf), "%02d:%02d:%02d", time.hour, time.minute, time.second);
                return time_buf;
  - id: lvgl_update_date
    then:
      - if:
          condition:
            not: lvgl.is_paused
          then:
            lvgl.label.update:
              id: header_date
              text: !lambda |-
                static const char* const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
                static char date_buf[16];
                auto now = id(sntp_time).now();
                snprintf(date_buf, sizeof(date_buf), "%s %02d, %d", mon_names[now.month-1], now.day_of_month, now.year);
                return date_buf;
  - id: lvgl_update_soc
    parameters:
      soc: float
    then:
      - if:
          condition:
            not: lvgl.is_paused
          then:
            - lvgl.arc.update:
                id: soc_arc
                value: !lambda return soc;
                indicator:
                  arc_color: !lambda |-
                    auto color = id(color_red).gradient(id(color_green), soc * 2.55);
                    return lv_color_make(color.red, color.green, color.blue);
            - lvgl.label.update:
                id: soc_label
                text:
                  format: "%f%%"
                  args: soc
  - id: lvgl_pause
    mode: single
    then:
      - if:
          condition:
            - lambda: return !id(display_lock);
          then:
            - light.turn_off: backlight
            - lvgl.page.show: blank_page
            - lvgl.widget.hide: header
            - delay: 1s
            - lvgl.pause
  - id: lvgl_resume
    mode: single
    then:
      - if:
          condition:
            lvgl.is_paused
          then:
            - lvgl.resume
            - lvgl.page.show: main_page
            - lvgl.widget.show: header
            - light.turn_on: backlight
  - id: update_led
    mode: single
    parameters:
      l_text: string
      l_color: esphome::Color
    then:
      - lvgl.label.update:
          id: status_label
          text: !lambda return l_text.c_str();
      - lvgl.led.update:
          id: status_led
          color: !lambda |-
            return lv_color_make(l_color.red, 
              l_color.green, l_color.blue);
  - id: turn_off
    mode: single
    then:
      - switch.turn_off: contactor_relay
      - script.execute:
          id: update_led
          l_text: 'Off'
          l_color: off_color
  - id: turn_on
    mode: single
    parameters:
      precharge: bool
    then:
      - if:
          condition:
            lambda: 'return precharge;'
          then:
            - globals.set:
                id: display_lock
                value: 'true'
            - script.execute:
                id: update_led
                l_text: 'Precharging'
                l_color: 0xFFFB00
            - switch.turn_on: precharge_relay
            - wait_until:
                condition:
                  binary_sensor.is_on: precharge_sensor
                timeout: 60s # remove on live
            - switch.turn_on: contactor_relay
            - switch.turn_off: precharge_relay
            - globals.set:
                id: display_lock
                value: 'false'
          else:
            - switch.turn_on: contactor_relay
      - script.execute:
          id: update_led
          l_text: 'On'
          l_color: on_color
