# source ../esphome/bin/activate
# python3 -m esphome run battery-controller-sdl.yaml

substitutions:
  device_name: battery-controller

packages:
  device_common: !include .sdl_device_common.yaml
  lvgl-ui: !include battery-controller/lvgl-ui.yaml
  jkbms-faker: !include battery-controller/jkbms-sdl-faker.yaml

globals:
  - id: current_tile_num
    type: uint8_t
    initial_value: '0'
  - id: is_automatic_tile_change
    type: bool
    initial_value: 'false'

time:
  - id: sntp_time
    platform: host
    timezone: Europe/Kievs

esphome:
  name: battery-controller-sdl
  friendly_name: battery-controller-sdl

logger:

touchscreen:
  - platform: sdl
    id: !extend touch
    on_release:
      - script.execute: lvgl_resume

output:
  - platform: template
    id: backlight_out
    type: float
    write_action:
      lambda: ;

light:
  - platform: monochromatic
    id: backlight
    output: backlight_out

display:
  - platform: sdl
    id: !extend sdl_display
    dimensions:
      width: 480
      height: 320
