# source ../esphome/bin/activate
# python3 -m esphome run battery-status-display-sdl.yaml

substitutions:
  device_name: battery-status-display
  device_name_underscore: battery_status_display

globals:
  - id: voltage
    type: float
    initial_value: '27.5'
  - id: soc
    type: float
    initial_value: '97'
  - id: current
    type: float
    initial_value: '-3.7'
  - id: power
    type: float
    initial_value: '2100'
  - id: min_cell_voltage
    type: float
    initial_value: '3.21'
  - id: max_cell_voltage
    type: float
    initial_value: '3.29'
  - id: cell_temp
    type: float
    initial_value: '29.1'
  - id: mos_temp
    type: float
    initial_value: '30.1'

packages:
  device_common: !include .sdl_device_common.yaml
  # device_common: !include .device_common.yaml
  # jkbms_disp_port: !include 
  #   file: battery-status-display/jkbms-display-port.yaml
  #   vars:
  #     rx_pin: GPIO20
  lvgl-ui: !include battery-status-display/lvgl-ui.yaml

touchscreen:
  - platform: sdl
    id: !extend touch
    on_release:
      - script.execute: lvgl_resume

display:
  - platform: sdl
    id: !extend sdl_display
    dimensions:
      width: 240
      height: 240

interval:
  - interval: 1s
    id: update_labels_interval
    then:
      script.execute: lvgl_update_values

script:
  - id: lvgl_update_values
    mode: single
    then:
      - lvgl.label.update:
          id: soc_label
          text:
            format: "%.0f%%"
            args: ['id(soc)']
      - lvgl.label.update:
          id: power_label
          text:
            format: "%.0fW"
            args: ['id(power)']
      - lvgl.label.update:
          id: cap_label
          text:
            format: "%.1fAh"
            args: ['id(soc) * 1.05']
      - lvgl.label.update:
          id: current_label
          text:
            format: "%.1fA"
            args: ['id(current)']
      - lvgl.label.update:
          id: min_cell_v_label
          text:
            format: "%.3fV"
            args: ['id(min_cell_voltage)']
      - lvgl.label.update:
          id: max_cell_v_label
          text:
            format: "%.3fV"
            args: ['id(max_cell_voltage)']
      - lvgl.label.update:
          id: cell_temp_label
          text:
            format: "%.1fC"
            args: ['id(cell_temp)']
      - lvgl.label.update:
          id: mos_temp_label
          text:
            format: "%.1fC"
            args: ['id(mos_temp)']

output:
  - platform: template
    id: backlight_out
    type: float
    write_action:
      lambda: ;

light:
  - platform: monochromatic
    id: backlight
    output: backlight_out
