substitutions:
  device_name: boiler-relay
  device_name_underscore: boiler_relay
  relay_pin: GPIO12
  button_pin: GPIO0
  delay_time: 3min

packages:
  device_common: !include .device_common.yaml
  delayed_start: !include .sonoff_delayed_start.yaml

esphome:
  name: ${device_name} 
  platform: ESP8266
  board: esp01_1m

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

status_led:
  pin:
    number: GPIO13
    inverted: yes

web_server:
  port: 4576
  ota: false

sensor:
  - platform: cse7766
    current:
      name: "Boiler Current"
      id: "boiler_current"
    voltage:
      name: "Boiler Voltage"
      id: "boiler_voltage"
    power:
      name: "Boiler Power"
      id: "boiler_power"
      on_value_range:
        - below: 10.0
          then:
            - binary_sensor.template.publish:
                id: boiler_state
                state: "OFF"
        - above: 10.0
          then:
            - binary_sensor.template.publish:
                id: boiler_state
                state: ON
    energy:
      name: "Boiler Energy"
      id: "boiler_energy"
  - platform: total_daily_energy
    name: "Boiler Total Daily Energy"
    power_id: "boiler_power"
    id: "boiler_daily_energy"
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy

binary_sensor:
  - platform: template
    name: "Boiler state"
    id: boiler_state