substitutions:
  device_name: boiler-cutoff
  device_name_underscore: boiler_cutoff
  relay_pin: GPIO12
  delay_time: 5m

packages:
  device_common: !include .device_common.yaml

globals:
  - id: relay_state
    type: boolean
    restore_value: true
    initial_value: "true"

esphome:
  name: ${device_name} 
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true
  on_boot:
    priority: 600
    then:
      - if:
          condition:
            - lambda: 'return id(relay_state);'
          then:
            - if:
                condition:
                  - lambda: 'return system_get_rst_info()->reason == 0;'    
                then:
                  - delay: ${delay_time}
            - switch.turn_on: relay_phy

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: relay_switch
    internal: true
    on_press:
      - switch.toggle: relay_phy

switch:
  - platform: gpio
    id: relay_phy
    name: "${device_name} relay"
    pin: ${relay_pin}
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - lambda: id(relay_state) = true;
    on_turn_off:
      - lambda: |-
          static bool initial = true;
          if (initial) {
            initial = false;
          } else {
            id(relay_state) = false;
          }

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: cse7766
    current:
      name: "${device_name} Current (A)"
      id: "${device_name_underscore}_current"
    voltage:
      name: "${device_name} Voltage (V)"
      id: "${device_name_underscore}_voltage"
    power:
      name: "${device_name} Power (W)"
      id: "${device_name_underscore}_power"
    energy:
      name: "${device_name} Energy (Wh)"
      id: "${device_name_underscore}_energy"
  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy (kWh)"
    power_id: "${device_name_underscore}_power"
    id: "${device_name_underscore}_daily_energy"
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy
