esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32dev

substitutions:
  device_name: "cam-test" 

packages:
  device_common: !include .device_common.yaml
  
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: ${device_name} cam
  resolution: 320x240