esphome:
  name: haier-adults
  platform: ESP8266
  board: d1_mini
  includes:
    - Haier.h

logger:
  level: DEBUG
  baud_rate: 0

status_led:
  pin: GPIO2

api:

ota:
  password: "ebf6abfbdd0c992d67c5b87d5a8a05e8"

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Haier-Adults"
    password: "engz1DfWcmQ7"

captive_portal:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Kiev 

climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "Haier Adults"