globals:
  - id: intensity_red
    type: float
    restore_value: no
    initial_value: '0'
  - id: intensity_green
    type: float
    restore_value: no
    initial_value: '0'
  - id: intensity_blue
    type: float
    restore_value: no
    initial_value: '0'

substitutions:
  device_name: lobby-led-light

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32doit-devkit-v1
  on_boot:
    priority: 300.0
    then:
      - script.execute: turn_on_light

light:
  - platform: fastled_clockless
    id: lobbyledlight
    chipset: WS2812B
    pin: GPIO13
    num_leds: 300
    rgb_order: GRB
    name: "Lobby Led Light"
    restore_mode: ALWAYS_OFF
    default_transition_length: 1500ms
    effects:
      - flicker:
          name: flicker
          alpha: 95%
          intensity: 1.5%
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values 1
          speed: 1
          width: 50
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values 2
          speed: 100
          width: 50
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values 3
          speed: 50
          width: 70

time:
  - platform: sntp
    on_time_sync:
      then:
        - script.execute: set_daylight_color

sun:
  latitude: 50.391968°
  longitude: 30.557317°
  on_sunrise:
    then:
      - script.execute: set_daylight_color
  on_sunset:
    then:
      - script.execute: set_daylight_color

script:
  - id: turn_on_light
    then:
      - light.turn_on:
          id: lobbyledlight
          brightness: 80%
          red: 1
          green: 1
          blue: 1
          effect: none
  - id: set_light_color
    then:
      - light.control:
          id: lobbyledlight
          red: !lambda |-
            return id(intensity_red);
          green: !lambda |-
            return id(intensity_green);
          blue: !lambda |-
            return id(intensity_blue);
          transition_length: 1000ms
  - id: set_daylight_color
    then:
      - script.wait: turn_on_light
      - if:
          condition:
            sun.is_above_horizon
          then:
            - globals.set:
                id: intensity_red
                value: '1.0'
            - globals.set:
                id: intensity_green
                value: '.67'
            - globals.set:
                id: intensity_blue
                value: '.11'
          else:
            - globals.set:
                id: intensity_red
                value: '.0'
            - globals.set:
                id: intensity_green
                value: '1.0'
            - globals.set:
                id: intensity_blue
                value: '1.0'
      - script.execute: set_light_color
