substitutions:
  device_name: mains-cutoff

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

logger:
  level: DEBUG
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: pzemac
    current:
      name: "Mains Current"
      id: mains_current
    voltage:
      name: "Mains Voltage"
      id: mains_voltage
    energy:
      name: "Mains Energy"
      id: mains_energy
    power:
      name: "Mains Power"
      id: mains_power
    frequency:
      name: "Mains Frequency"
      id: mains_frequency
    power_factor:
      name: "Mains Power Factor"
      id: mains_power_factor
    update_interval: 60s

  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy"
    power_id: mains_power
    id: mains_daily_energy
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy

ota:
  password: !secret ota_password
  id: my_ota

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: relay_switch
    on_press:
      - switch.toggle: relay
    internal: true

switch:
  - platform: gpio
    id: relay
    name: "Cutoff relay"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF

button:
  - platform: template
    name: "Reset PZEM-004T"
    id: reset_pzem_004t
    on_press:
      - uart.write: [0x01, 0x42, 0x80, 0x11]
  - platform: restart
    id: mains_cutoff_restart
    name: "Mains Cutoff Restart"

status_led:
  pin:
    number: GPIO13
    inverted: yes
