first-need-to-be-tested: 1!

substitutions:
  device_name: mains-cutoff

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

globals:
  - id: relay_state
    type: boolean
    restore_value: true
    initial_value: "true"
  - id: manual
    type: boolean
    restore_value: false
    initial_value: "false"

logger:
  level: DEBUG
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: pzemac
    current:
      name: "Mains Current"
      id: mains_current
    voltage:
      name: "Mains Voltage"
      id: mains_voltage
    energy:
      name: "Mains Energy"
      id: mains_energy
    power:
      name: "Mains Power"
      id: mains_power
    frequency:
      name: "Mains Frequency"
      id: mains_frequency
    power_factor:
      name: "Mains Power Factor"
      id: mains_power_factor
    update_interval: 60s

  - platform: total_daily_energy
    name: "${device_name} Total Daily Energy"
    power_id: mains_power
    id: mains_daily_energy
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: relay_switch
    on_press:
      - switch.toggle: relay_phy
    internal: true

switch:
  - platform: template
    id: relay
    name: "Cutoff relay"
    restore_state: no
    turn_on_action:
      - script.execute: turn_relay_on
    turn_off_action:
      - script.execute: turn_relay_off
    lambda: |-
      return id(relay_state);
  - platform: gpio
    id: relay_phy
    pin: GPIO12
    internal: true

script:
  - id: turn_relay_on
    then:
      - if:
          condition:
            lambda: |-
              return !id(manual);
          then:
            delay: "00:01:00"
          else:
            globals.set:
              id: manual
              value: "true"
      - switch.turn_on: relay_phy
  - id: turn_relay_off
    then:
      - switch.turn_off: relay_phy

button:
  - platform: template
    name: "Reset PZEM-004T"
    id: reset_pzem_004t
    on_press:
      - uart.write: [0x01, 0x42, 0x80, 0x11]
  - platform: restart
    id: mains_cutoff_restart
    name: "Mains Cutoff Restart"

status_led:
  pin:
    number: GPIO13
    inverted: yes
