substitutions:
  device_name: mains-cutoff

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name} 
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: relay_switch
    on_press:
      - switch.toggle: relay
    internal: true

switch:
  - platform: gpio
    id: relay
    name: "Cutoff relay"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF

status_led:
  pin:
    number: GPIO13
    inverted: yes
