substitutions:
  device_name: pc-wol-button
  device_name_underscore: pc_wol_button
  bearpaw_pc_mac_addr: !secret bearpaw_pc_mac_addr

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32-c3-devkitm-1
  includes:
    - pc-wol-button/WakeOnLan.cpp
    - pc-wol-button/WakeOnLan.h
    - pc-wol-button/wol.h
    - pc-wol-button/clock.h

packages:
  device_common: !include .device_common.yaml

external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]
  - source: github://pr#5941
    components: [cst816]

logger:
  baud_rate: 0 #460800
#  hardware_uart: USB_SERIAL_JTAG

spi:
  mosi_pin: GPIO7
  clk_pin: GPIO6

i2c:
  sda: GPIO4
  scl: GPIO5

output:
  - platform: ledc
    pin: GPIO3
    id: gpio_3_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

text_sensor:
  - id: bearpaw_pc_state_text
    platform: homeassistant
    entity_id: device_tracker.bearpaw_l340_17_eth
  - id: bearpaw_pc_ip
    platform: homeassistant
    entity_id: device_tracker.bearpaw_l340_17_eth
    attribute: ip

binary_sensor:
  - id: bearpaw_pc_state
    platform: template
    internal: true
    lambda: |-
      return id(bearpaw_pc_state_text)->state == "home";
    
# time:
#   - id: !extend sntp_time
#     on_time:
#       # Lower the backlight at night.
#       - hours: 23
#         then:
#           - light.turn_on: 
#               id: backlight
#               brightness: 20%
#       - hours: 08
#         then:
#           - light.turn_on:
#               id: backlight
#               brightness: 100%

wifi:
  on_connect:
    - script.execute: prepare_wol

script:
  - id: prepare_wol
    mode: single
    then:
      lambda: wol_setup();
  - id: send_wol_packet
    mode: single
    then:
      lambda: wol_send("id(bearpaw_pc_mac_addr");

color:
  - id: text_wol_color
    # red: 100%
    # green: 5%
    # blue: 3%
    hex: af3a03
  - id: text_clock_color
    red: 0
    green_int: 53
    blue_int: 31
  - id: watchface_fg_color
    red: 10%
    blue: 0%
    green: 10%
  - id: my_blue
    blue: 100%
  - id: my_red
    red: 100%
  - id: my_green
    green: 100%
  - id: my_white
    red: 100%
    blue: 100%
    green: 100%
  - id: my_yellow
    hex: ffff00

font:
  - file: 'gfonts://Roboto'
    id: font_16
    size: 16
 # - file: pc-wol-button/flip_clock_font.ttf
 #   id: flip_clock_font
 #   size: 50
 #   glyphs: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':']

image:
  - id: wifi_icon
    file: mdi:wifi
    resize: 16x16
  - id: pc_icon
    file: mdi:laptop
    resize: 16x16

display:
#  - platform: ili9xxx
#    model: gc9a01
# Above is for when or if this is merged into the ili9xxx platform
  - platform: gc9a01
    id: watchface
    cs_pin: GPIO10
    dc_pin: GPIO2
    width: 240
    height: 240
    eight_bit_color: false
    rotation: 270
    update_interval: 1s
    lambda: |-
      Color marks_color = id(text_clock_color);
      Clock::draw_watch_face(&it, 120, 120, 107, 100, id(sntp_time).now(),
        id(watchface_fg_color), marks_color, marks_color, marks_color);
      if (id(bearpaw_pc_state)->state) {
        it.image(100, 40, id(pc_icon));
      }
      it.strftime(120, 70, id(font_16), id(text_clock_color), TextAlign::CENTER, "%A %b %d", id(sntp_time).now());
      it.strftime(120, 90, id(font_16), id(text_clock_color), TextAlign::CENTER, "%H:%M:%S", id(sntp_time).now());
      it.printf(120, 110, id(font_16), id(text_wol_color), TextAlign::CENTER, "%s: %s", id(bearpaw_pc_state_text)->state.c_str(), id(bearpaw_pc_ip)->state.c_str());
      bool is_sending_wol = id(send_wol_packet).is_running();
      if (!is_sending_wol)
        it.print(120, 150, id(font_16), id(text_wol_color), TextAlign::CENTER, "Press to wake the PC");
      else
        it.print(120, 150, id(font_16), id(text_wol_color), TextAlign::CENTER, "Sending WOL packet");

touchscreen:
  id: cst816d
  platform: cst816
  interrupt_pin: GPIO0
  reset_pin: GPIO1
  transform:
    swap_xy: true
    mirror_y: true
  on_touch:
    - lambda: |-
        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
        );
    - script.execute: send_wol_packet
    - component.update: watchface
    - delay: 5s
    - component.update: watchface
