substitutions:
  device_name: pc-wol-button
  device_name_underscore: pc_wol_button

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32-c3-devkitm-1

packages:
  device_common: !include .device_common.yaml

external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]
  - source: github://pr#5941
    components: [cst816]
  - source: github://GadgetFactory/CST816S_touchscreen@1.0.0

spi:
  mosi_pin: GPIO7
  clk_pin: GPIO6

i2c:
  sda: GPIO4
  scl: GPIO5

output:
  - platform: ledc
    pin: GPIO3
    id: gpio_3_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_green
    red: 3%
    green: 100%
    blue: 5%
  - id: my_blue
    red: 3%
    green: 5%
    blue: 100%

time:
  - id: !extend sntp_time
    on_time:
      # Turn off the backlight at night.
      - hours: 23
        then:
          - light.turn_off: backlight
      - hours: 08
        then:
          - light.turn_on: backlight

image:
  - file: mdi:power
    id: power_img
    resize: 200x200

display:
#  - platform: ili9xxx
#    model: gc9a01
# Above is for when or if this is merged into the ili9xxx platform
  - platform: gc9a01
    id: watchface
    reset_pin: GPIO1
    cs_pin: GPIO10
    dc_pin: GPIO2
    rotation: 270
    pages:
      - id: power_on_btn_page
        lambda: |-
          it.image(20, 20, id(power_img));
      - id: power_on_progress_page
        lambda: |-
          it.strftime(120,80, id(font_16), id(my_blue), TextAlign::CENTER, "%A %b %d", id(esptime).now());
          it.strftime(120,120, id(font_32), TextAlign::CENTER, "%I:%M %p", id(esptime).now());
          it.printf(120, 170, id(font_32), id(my_green), TextAlign::CENTER, "Now: %.1f°", id(outdoor_temperature).state);
          it.circle(120, 120, 115, id(my_red));

button:
  - platform: wake_on_lan
    name: "Start the PC"
    id: bearpaw_pc_wol_button
    target_mac_address: !secret bearpaw_pc_mac_addr
    internal: true

text_sensor:
  - platform: CST816S_touchscreen
    id: my_touch_screen
    on_value:
      then:
        - if:
            condition:
              and:
                - text_sensor.state:
                    id: my_touch_screen
                    state: 'SINGLE CLICK'
                - display.is_displaying_page: power_on_btn_page
            then:
              - button.press: bearpaw_pc_wol_button
              - display.page.show: power_on_progress_page
              - delay: 10s
              - display.page.show: power_on_btn_page

 # Have found that the 'single click' does not always register hence also using 'long press' to toggle light 
        - if:
            condition:
              and:
                - text_sensor.state:
                    id: my_touch_screen
                    state: 'LONG PRESS'
                - display.is_displaying_page: power_on_btn_page
            then:
              - button.press: bearpaw_pc_wol_button
              - display.page.show: power_on_progress_page
              - delay: 10s
              - display.page.show: power_on_btn_page

# touchscreen:
#   platform: cst816
#   interrupt_pin: 0
#   #reset_pin: GPIO1

# binary_sensor:
#   - platform: touchscreen
#     name: Power on button
#     id: power_on_button
#     x_min: 20
#     x_max: 20
#     y_min: 220
#     y_max: 220
#     page_id: power_on_btn_page
#     on_click: 
#       - button.press: bearpaw_pc_wol_button
#       - display.page.show: power_on_progress_page
