substitutions:
  device_name: pc-wol-button
  device_name_underscore: pc_wol_button
  bearpaw_pc_mac_addr: !secret bearpaw_pc_mac_addr

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32-c3-devkitm-1
  includes:
    - pc-wol-button/WakeOnLan.cpp
    - pc-wol-button/WakeOnLan.h
    - pc-wol-button/pc_wol_button.h

packages:
  device_common: !include .device_common.yaml

external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]
  - source: github://pr#5941
    components: [cst816]

logger:
  baud_rate: 0 #460800
#  hardware_uart: USB_SERIAL_JTAG

spi:
  mosi_pin: GPIO7
  clk_pin: GPIO6

i2c:
  sda: GPIO4
  scl: GPIO5

output:
  - platform: ledc
    pin: GPIO3
    id: gpio_3_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

# time:
#   - id: !extend sntp_time
#     on_time:
#       # Lower the backlight at night.
#       - hours: 23
#         then:
#           - light.turn_on: 
#               id: backlight
#               brightness: 20%
#       - hours: 08
#         then:
#           - light.turn_on:
#               id: backlight
#               brightness: 100%

wifi:
  on_connect:
    - script.execute: prepare_wol

script:
  - id: prepare_wol
    mode: single
    then:
      lambda: wol_setup();
  - id: send_wol_packet
    mode: single
    then:
      lambda: wol_send("id(bearpaw_pc_mac_addr");

color:
  - id: my_blue
    red: 3%
    green: 5%
    blue: 100%
  - id: flip_clock_color
    red: 0
    green_int: 53
    blue_int: 31
  - id: watchface_bg_color
    red: 9%
    blue: 8%
    green: 9%
  - id: watchface_fg_color
    red: 75%
    blue: 75%
    green: 75%

# image:
 #  - id: watchface_bg
  #   file: pc-wol-button/watchface.bmp
 #    type: BINARY

font:
  - file: 'gfonts://Roboto'
    id: font_16
    size: 16
  - file: pc-wol-button/flip_clock_font.ttf
    id: flip_clock_font
    size: 50
    glyphs: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':']

number:
  - id: c_r
    name: Color red
    platform: template
    min_value: 0
    max_value: 255
    step: 0
    optimistic: true
    initial_value: 100
  - id: c_g
    name: Color green
    platform: template
    min_value: 0
    max_value: 255
    step: 0
    optimistic: true
    initial_value: 100
  - id: c_b
    name: Color blue
    platform: template
    min_value: 0
    max_value: 255
    step: 0
    optimistic: true
    initial_value: 100

display:
#  - platform: ili9xxx
#    model: gc9a01
# Above is for when or if this is merged into the ili9xxx platform
  - platform: gc9a01
    id: watchface
    cs_pin: GPIO10
    dc_pin: GPIO2
    width: 240
    height: 240
    eight_bit_color: false
    rotation: 270
    update_interval: 1s
    lambda: |-
      auto color = Color(id(c_r)->state, id(c_g)->state, id(c_b)->state);
      draw_bezel(&it, color, 120, 120, 107, 100);
      //it.image(0, 0, id(watchface_bg), color, id(watchface_fg_color));
      it.strftime(120, 70, id(font_16), id(flip_clock_color), TextAlign::CENTER, "%A %b %d", id(sntp_time).now());
      //it.strftime(120, 120, id(flip_clock_font), id(flip_clock_color), TextAlign::CENTER, "%H:%M:%S", id(sntp_time).now());
      //bool is_sending_wol = id(send_wol_packet).is_running();
      //if (!is_sending_wol)
      //  it.print(120, 180, id(font_16), id(my_blue), TextAlign::CENTER, "Press to wake the PC");
      //else
      //  it.print(120, 180, id(font_16), id(my_blue), TextAlign::CENTER, "Sending WOL packet");
      //it.circle(120, 120, 115, id(flip_clock_color));

touchscreen:
  id: cst816d
  platform: cst816
  interrupt_pin: GPIO0
  reset_pin: GPIO1
  transform:
    swap_xy: true
    mirror_y: true
  on_touch:
    - lambda: |-
        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
        );
    - script.execute: send_wol_packet
    - component.update: watchface
    - delay: 5s
    - component.update: watchface
