substitutions:
  device_name: pc-wol-button
  device_name_underscore: pc_wol_button

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32-c3-devkitm-1

packages:
  device_common: !include .device_common.yaml

external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]
  - source: github://pr#5941
    components: [cst816]

spi:
  mosi_pin: GPIO7
  clk_pin: GPIO6

i2c:
  sda: GPIO4
  scl: GPIO5

output:
  - platform: ledc
    pin: GPIO3
    id: gpio_3_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_green
    red: 3%
    green: 100%
    blue: 5%
  - id: my_blue
    red: 3%
    green: 5%
    blue: 100%

time:
  - id: !extend sntp_time
    on_time:
      # Turn off the backlight at night.
      - hours: 23
        then:
          - light.turn_off: backlight
      - hours: 08
        then:
          - light.turn_on: backlight

image:
  - file: mdi:power
    id: power_img
    resize: 200x200

animation:
  - file: progress.gif
    id: progress_animation

display:
#  - platform: ili9xxx
#    model: gc9a01
# Above is for when or if this is merged into the ili9xxx platform
  - platform: gc9a01
    id: watchface
    #reset_pin: GPIO1
    cs_pin: GPIO10
    dc_pin: GPIO2
    rotation: 90
    lambda: |-
      it.image(20, 20, id(power_img));
    # pages:
    #   - id: power_on_btn_page
    #     lambda: |-
    #       it.image(20, 20, id(power_img));
    #   - id: power_on_progress_page
    #     lambda: |-
    #       it.image(20, 20, id(progress_animation));

button:
  - platform: wake_on_lan
    name: "Start the PC"
    id: bearpaw_pc_wol_button
    target_mac_address: !secret bearpaw_pc_mac_addr
    internal: true

touchscreen:
  platform: cst816
  interrupt_pin: GPIO0
  reset_pin: GPIO1

binary_sensor:
  - platform: touchscreen
    name: Power on button
    id: power_on_button
    x_min: 100
    x_max: 140
    y_min: 100
    y_max: 140
    #page_id: power_on_btn_page
    on_click: 
      - button.press: bearpaw_pc_wol_button
    #  - display.page.show: power_on_progress_page
