substitutions:
  device_name: "powmr-wifi-dongle-32"
  uart_tx_pin: GPIO16
  uart_rx_pin: GPIO17
  friendly_name: "POWMR WiFi dongle 32"

esphome:
  name: powmr-wifi-dongle-32
  friendly_name: powmr-wifi-dongle-32

light:
  - platform: status_led
    id: status_led_
    pin: GPIO2

packages:
  devicecommon: !include .device_common.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino

globals:
  - id: inverter_on
    type: boolean
    initial_value: 'false'

uart:
  - id: powmr_uart
    tx_pin: ${uart_tx_pin}
    rx_pin: ${uart_rx_pin}
    baud_rate: 2400
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   sequence:
    #     - lambda: |-
    #         UARTDebug::log_hex(direction, bytes, ':');

pipsolar:
  - id: powmr_inverter
    uart_id: powmr_uart

binary_sensor:
  - platform: pipsolar
    pipsolar_id: powmr_inverter
    configuration_status:
      id: powmr_configuration_status
      name: Powmr configuration_status
    backlight_on: 
      id: powmr_backlight_on
      name: Powmr backlight on

sensor:
  - platform: pipsolar
    pipsolar_id: powmr_inverter
    grid_voltage:
      id: powmr_grid_voltage
      name: Powmr grid voltage
    battery_voltage:
      id: powmr_battery_voltage
      name: Powmr battery voltage
    battery_charging_current:
      id: powmr_battery_charging_current
      name: Powmr battery charging current
    battery_discharge_current: 
      id: powmr_battery_discharging_current
      name: Powmr battery discharging current
    ac_output_apparent_power:
      id: powmr_ac_output_apparent_power
      name: Powmr AC output apparent power
    ac_output_active_power:
      id: powmr_ac_output_active_power
      name: Powmr AC output active power
