substitutions:
  device_name: "powmr-wifi-dongle-32"
  uart_tx_pin: GPIO7
  uart_rx_pin: GPIO21
  friendly_name: "POWMR WiFi dongle 32"

esphome:
  name: powmr-wifi-dongle-32
  friendly_name: powmr-wifi-dongle-32

output:
  - platform: gpio
    id: pwr_led
    pin:
      number: GPIO20
      inverted: true
  - platform: gpio
    id: com_led
    pin: GPIO8
  - platform: gpio
    id: net_led
    pin: GPIO9

# leds: D1, D2, D3, D4
light:
  # SRV
  - platform: status_led
    id: status_led_
    pin:
      number: GPIO10
      inverted: true

packages:
  devicecommon: !include .device_common.yaml

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

globals:
  - id: inverter_on
    type: boolean
    initial_value: 'false'

wifi:
  on_connect:
    - output.turn_on: net_led
  on_disconnect:
    - output.turn_off: net_led

uart:
  - id: powmr_uart
    tx_pin: ${uart_tx_pin}
    rx_pin: ${uart_rx_pin}
    baud_rate: 2400
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   sequence:
    #     - lambda: |-
    #         UARTDebug::log_hex(direction, bytes, ':');

pipsolar:
  - id: powmr_inverter
    uart_id: powmr_uart

binary_sensor:
  - platform: pipsolar
    pipsolar_id: powmr_inverter
    backlight_on: 
      id: powmr_backlight_on
      name: Powmr backlight on
    switch_on:
      id: powmr_switch_on
      name: Powmr switch on
    warnings_present:
      id: powmr_warnings_present
      name: Powmr warnings present
    faults_present:
      id: powmr_faults_present
      name: Powmr faults present
    fault_bus_over:
      id: powmr_bus_overvoltage_fault
      name: Powmr bus overvoltage fault
    fault_inverter_voltage_too_high:
      id: powmr_inverter_overvoltage_fault
      name: Powmr inverter overvoltage fault
    warning_battery_voltage_high:
      id: powmr_batt_overvoltage_warning
      name: Powmr battery overvoltage warning

sensor:
  - platform: pipsolar
    pipsolar_id: powmr_inverter
    grid_voltage:
      id: powmr_grid_voltage
      name: Powmr grid voltage
    battery_voltage:
      id: powmr_battery_voltage
      name: Powmr battery voltage
    battery_charging_current:
      id: powmr_battery_charging_current
      name: Powmr battery charging current
    battery_discharge_current: 
      id: powmr_battery_discharging_current
      name: Powmr battery discharging current
    ac_output_apparent_power:
      id: powmr_ac_output_apparent_power
      name: Powmr AC output apparent power
    ac_output_active_power:
      id: powmr_ac_output_active_power
      name: Powmr AC output active power
    inverter_heat_sink_temperature:
      id: powmr_invertet_twmperature
      name: Powmr inverter temperature

text_sensor:
  - platform: pipsolar
    pipsolar_id: powmr_inverter
    device_mode:
      id: powmr_device_mode
      name: Powmr device mode