esphome:
  name: pylon-protocol-emulator
  friendly_name: pylon-protocol-emulator
  includes:
    - pylon-protocol-emulator/custom_component.cpp
    - pylon-protocol-emulator/pylontech_rs485_low_voltage.h
    - pylon-protocol-emulator/pylontech_rs485_low_voltage.cpp

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  device_common: !include .device_common.yaml

status_led:
  pin:
    number: GPIO2
    inverted: yes

uart:
  id: uart_0
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600
  debug:
    direction: BOTH
    dummy_receiver: false

custom_component:
- lambda: |-
    auto my_custom = new PylontechEmulatorComponent(id(uart_0));
    return {my_custom};
