substitutions:
  device_name: pylon-protocol-emulator
  name: Pylon protocol emulator

esphome:
  name: pylon-protocol-emulator
  friendly_name: pylon-protocol-emulator
  includes:
    - pylon-protocol-emulator/pylontech_rs485_low_voltage.h
    - pylon-protocol-emulator/pylontech_rs485_low_voltage.cpp
    - pylon-protocol-emulator/custom_component.h

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  pace_bms_common: !include .pace-bms-base.yaml

modbus:
  - id: !remove modbus0

custom_component:
- lambda: |-
    auto comp = new PylontechEmulatorComponent(id(uart_0));
    return {comp};
