substitutions:
  device_name: pylon-protocol-listener
  name: Pylon protocol listener

esphome:
  name: pylon-protocol-listener
  friendly_name: pylon-protocol-listener

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  pace_bms_common: !include .pace-bms-base.yaml

modbus:
  - id: !remove modbus0

# Enable logging
logger:
    

button:
  - id: send_frame
    name: Send frame
    platform: template
    on_press: 
      uart.write: [0x7E, 0x32, 0x30, 0x30, 0x32, 0x34, 0x36, 0x36, 0x31, 0x45, 0x30, 0x30, 0x32, 0x30, 0x31, 0x46, 0x44, 0x33, 0x33, 0x0D]

# interval:
#  - interval: 500ms
  #  then: 
  #    uart.write: [0x7E, 0x32, 0x30, 0x30, 0x32, 0x34, 0x36, 0x36, 0x31, 0x45, 0x30, 0x30, 0x32, 0x30, 0x31, 0x46, 0x44, 0x33, 0x33, 0x0D]