substitutions:
    device_name: "rock5b-power-guard"
    device_name_underscore: "rock5b_power_guard"

globals:
  - id: power_state
    type: bool
    restore_value: true
    initial_value: "true"

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  esp8266_restore_from_flash: true

# status_led:
#   pin:
#     number: D4
#     inverted: true

switch:
  - platform: gpio
    pin: D1
    id: relay
    internal: true

light:
  - platform: status_led
    id: "status_led_"
    internal: true
    pin:
      number: D4
      inverted: true

binary_sensor:
  - platform: gpio
    id: "${device_name_underscore}_external_power"
    pin: 
      number: D7
      inverted: true
    name: "${device_name} external power"
    on_press:
      - lambda: ESP_LOGD("WATCHER", "Added power");
      - lambda: id(power_state) = true;
      - light.turn_on: status_led_
    on_release:
      - lambda: ESP_LOGD("WATCHER", "Removed power");
      - lambda: id(power_state) = false;
      - light.turn_off: status_led_

script:
  - id: reset_rock5b
    then:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
