substitutions:
    device_name: "rock5b-power-guard"
    device_name_underscore: "rock5b_power_guard"

packages:
  device_common: !include .device_common.yaml

deep_sleep:
  sleep_duration: 120s

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

web_server:
  port: 80
  version: 3

status_led:
  pin:
    number: D4
    inverted: true

switch:
  - platform: gpio
    pin: D1
    id: "${device_name_underscore}_relay"
    name: "${device_name} relay"
    #internal: true
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    id: "${device_name_underscore}_external_power"
    pin: 
      number: D7
      inverted: true
    name: "${device_name} external power"
    publish_initial_state: true
    on_state:
      - script.execute: handle_power_sensor
  - platform: gpio
    id: "${device_name_underscore}_rock5b_is_on"
    pin:
      number: D6
      inverted: true
    name: "${device_name} rock5b is on"
    publish_initial_state: true

script:
  - id: turn_on_rock5b
    mode: single
    then:
      - switch.turn_on: "${device_name_underscore}_relay"
      - wait_until:
          condition:
            binary_sensor.is_on: "${device_name_underscore}_rock5b_is_on"
          timeout: 120s
  - id: turn_off_rock5b
    mode: single
    then:
      - wait_until:
          condition:
            binary_sensor.is_off: "${device_name_underscore}_rock5b_is_on"
          timeout: 120s
      - switch.turn_off: "${device_name_underscore}_relay"
  - id: wait_and_sleep
    mode: single
    then:
      - delay: 60s
      - deep_sleep.enter:
  - id: handle_power_sensor
    mode: single
    then:
      - lambda: |-
          auto power_state = id(${device_name_underscore}_external_power).state;
          if (power_state) {
            ESP_LOGD("WATCHER", "Power is on");
            auto reset_reason = system_get_rst_info()->reason;
            if (reset_reason == 5) {
              // awaked from deep sleep.
              id(turn_on_rock5b).execute();
            }
          } else {
            ESP_LOGD("WATCHER", "Power is off");
            id(wait_and_sleep).execute();
          }
