esphome:
  name: ${device_name}
  friendly_name: towel dryer relay

# TODO: calibrate
substitutions:
  device_name: towel-dryer-relay
  device_name_underscore: towel_dryer_relay
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

esp8266:
  board: esp01_1m

packages:
  device_common: !include .device_common.yaml

light:
  - platform: status_led
    id: led
    restore_mode: RESTORE_DEFAULT_ON
    internal: true
    pin:
      number: GPIO13
      inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
    id: "button_state"
    on_press:
      - switch.toggle: "button_switch"

switch:
  - platform: template
    name: "${device_name} - Switch"
    icon: mdi:power
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    id: "button_switch"
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_ON
    pin: GPIO14
    id: relay
    internal: true

sensor:
  - platform: total_daily_energy
    name: "${device_name} - Total daily energy (kWh)"
    id: "${device_name_underscore}_total_daily_energy"
    power_id: "${device_name_underscore}_power"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:calendar-clock

  # - platform: adc
  #   pin: VCC
  #   name: "${device_name} - VCC Volt"
  #   icon: mdi:flash-outline

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s
    current:
      name: "${device_name} - Current"
      id: "${device_name_underscore}_current"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:current-ac
    voltage:
      name: "${device_name} - Voltage"
      id: "${device_name_underscore}_voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
    power:
      name: "${device_name} - Power"
      id: "${device_name_underscore}_power"
      unit_of_measurement: W
      icon: mdi:gauge
