substitutions:
  device_name: water-cutoff

external_components:
  - source: github://dentra/esphome-components

packages:
  device_common: !include .device_common.yaml

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp-wrover-kit

status_led:
  pin: GPIO25

# CWX CR02 valve pinout:
# Yellow - common negative - relay_1 NO
# Red - open positive - relay_2 NO
# Blue - close positive - relay_2 NC

switch:
  - platform: gpio
    pin: GPIO21
    id: "relay_1"
    name: "Relay 1"
    internal: true
  - platform: gpio
    pin: GPIO19
    id: "relay_2"
    name: "Relay 2"
    internal: true
  - platform: gpio
    pin: GPIO18
    id: "relay_3"
    name: "Relay 3"
    internal: true
  - platform: gpio
    pin: GPIO05
    id: "relay_4"
    name: "Relay 4"
    internal: true
  - platform: template
    id: water_cutoff
    name: "Water cutoff"
    restore_state: yes
    turn_on_action:
      - switch.template.publish:
          id: water_cutoff
          state: ON
      - switch.turn_on: relay_1
      - switch.turn_off: relay_2
      - delay: 10000ms
      - switch.turn_off: relay_1
    turn_off_action:
      - switch.template.publish:
          id: water_cutoff
          state: OFF
      - switch.turn_on: relay_1
      - switch.turn_on: relay_2
      - delay: 10000ms
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2

binary_sensor:
  - platform: miot_sjws01lm
    mac_address: "54:EF:44:E5:1C:23"
    bindkey: "47b658e2288541239bb8ab4b79d75039"
    name: "Boiler Leak sensor"
    on_press:
      - switch.turn_on: water_cutoff
    battery_level:
      name: "Boiler Leak sensor battery level"
  - platform: miot_sjws01lm
    mac_address: "54:EF:44:E5:29:F6"
    bindkey: "0daf32121dbdd402144b0cf33ea70557"
    name: "Filter Leak sensor"
    on_press:
      - switch.turn_on: water_cutoff
    battery_level:
      name: "Filter Leak sensor battery level"
  - platform: miot_sjws01lm
    mac_address: "54:EF:44:E5:28:CD"
    bindkey: "b92ab1569a921ec21ad8519bd7ffddf3"
    name: "Shower Leak sensor"
    on_press:
      - switch.turn_on: water_cutoff
    battery_level:
      name: "Shower Leak sensor battery level"
  - platform: miot_sjws01lm
    mac_address: "54:EF:44:E5:12:9A"
    bindkey: "593d53a13d86832fdf2b0fe7cab13ec9"
    name: "Laundry Leak sensor"
    on_press:
      - switch.turn_on: water_cutoff
    battery_level:
      name: "Laundry Leak sensor battery level"
  - platform: miot_sjws01lm
    mac_address: "54:EF:44:E5:16:16"
    bindkey: "f925eb3dffc36fdb721ecd8f302f8bda"
    name: "Toilet Leak sensor"
    on_press:
      - switch.turn_on: water_cutoff
    battery_level:
      name: "Toilet Leak sensor battery level"
  - platform: miot_sjws01lm
    mac_address: "54:EF:44:E5:18:4A"
    bindkey: "b2354449e4782b6d326858011afb0f12"
    name: "Kitchen Leak sensor"
    on_press:
      - switch.turn_on: water_cutoff
    battery_level:
      name: "Kitchen Leak sensor battery level"
