substitutions:
  device_name: "powmr-wifi-dongle"
  inverter_voltage_offset: "0"
  update_interval: 30s # Minimum 10s recommended to avoid duplicate command errors
  select_skip_updates: "2"
  inverter_tx: GPIO1
  inverter_rx: GPIO3
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO3
  inverter_maximum_power: "10200"
  friendly_name: POWMR WiFi dongle
  version: "2"

globals:
  - id: inverter_on
    type: boolean
    initial_value: 'false'

packages:
  device_common: !include .device_common.yaml
  core_inv: !include powmr-wifi-dongle/core.yaml
  inv: !include powmr-wifi-dongle/inverter.yaml
      # - packages/grid.yaml
      # - packages/temperature.yaml
      # - packages/battery.yaml
      # - packages/battery-48v.yaml
      # - packages/pv.yaml
      # - packages/parallel.yaml
      # - packages/bms-48v.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp07
#  platformio_options:
#    build_flags:
#      - -DCONT_STACKSIZE=8196

logger:
  baud_rate: 0

# leds:
# NET - GPIO4
# COM - GPIO5
# SRV - GPIO0
status_led:
  pin: GPIO4

# output:
#   - platform: gpio
#     id: com_led_out
#     pin:
#       number: GPIO5
#       inverted: true
#   - platform: gpio
#     id: srv_led_out
#     pin:
#       number: GPIO0
#       inverted: true

# api:
#   on_client_connected:
#     - light.turn_on: srv_led
#   on_client_disconnected:
#     - light.turn_off: srv_led

# light:
#   - platform: binary
#     id: com_led
#     output: com_led_out
#     internal: true
#   - platform: binary
#     id: srv_led
#     output: srv_led_out
#     internal: true