- platform: template
  id: pbms_emul_temp_${item}
  name: "${name} Temperature: ${item}"
  optimistic: true
  min_value: -30
  max_value: 80
  unit_of_measurement: "ËšC"
  device_class: temperature
  step: 1