uart:
  - id: bms_uart
    baud_rate: 2400
    rx_pin: ${rx_pin}

jk_bms_display:
  - id: jkbms0
    uart_id: bms_uart

binary_sensor:
  - platform: jk_bms_display
    system_warning:
      id: jkbms_system_warn
      name: "JKBMS system warning"
      internal: true
    balancing_switch:
      id: jkbms_balancing_switch
      name: "JKBMS balancing switch"
    charging:
      id: jkbms_charging
      name: "JKBMS charging"
    discharging:
      id: jkbms_discharging
      name: "JKBMS discharging"
    cell_voltage_undervoltage_protection:
      id: jkbms_cell_uvp
      name: "JKBMS cell voltage undervoltage protection"
      internal: true
    cell_voltage_overvoltage_protection:
      id: jkbms_cell_ovp
      name: "JKBMS cell voltage overvoltage protection"
      internal: true
    overcurrent_protection:
      id: jkbms_ocp
      name: "JKBMS overcurrent protection"
      internal: true
    mosfet_overtemperature_protection:
      id: jkbms_mos_otp
      name: "JKBMS mosfet overtemperature protection"
      internal: true
    battery_temperature_protection:
      id: jkbms_batt_tp
      name: "JKBMS battery temperature protection"
      internal: true
    short_circuit_protection:
      id: jkbms_scp
      name: "JKBMS short circuit protection"
      internal: true
    coprocessor_communication_error:
      id: jkbms_cocpu_comm_err
      name: "JKBMS coprocessor communication error"
      internal: true
    balancer_wire_resistance_too_high:
      id: jkbms_high_wire_res
      name: "JKBMS balancer wire resistance too high"
      internal: true
    cell_count_mismatch:
      id: jkbms_cell_cnt_mismatch
      name: "JKBMS cell count mismatch"
      internal: true
  - platform: template
    id: jkbms_has_alarms
    name: "JKBMS has alarms"
    lambda: |-
      return id(jkbms_system_warn)->state ||
        id(jkbms_cell_uvp)->state ||
        id(jkbms_cell_ovp)->state ||
        id(jkbms_ocp)->state ||
        id(jkbms_mos_otp)->state ||
        id(jkbms_batt_tp)->state ||
        id(jkbms_scp)->state ||
        id(jkbms_cocpu_comm_err)->state ||
        id(jkbms_high_wire_res)->state ||
        id(jkbms_cell_cnt_mismatch)->state;

sensor:
  - platform: jk_bms_display
    total_voltage:
      id: jkbms_voltage_internal
      internal: true
      on_value:
        - globals.set:
            id: voltage
            value: !lambda return x;
    current:
      id: jkbms_current_internal
      internal: true
      on_value:
        - globals.set:
            id: current
            value: !lambda return x;
    power:
      id: jkbms_power_internal
      internal: true
      on_value:
        - globals.set:
            id: power
            value: !lambda return x;
    min_cell_voltage:
      id: jkbms_min_cell_voltage_internal
      internal: true
      on_value:
        - globals.set:
            id: min_cell_voltage
            value: !lambda return x;
    max_cell_voltage:
      id: jkbms_max_cell_voltage_internal
      internal: true
      on_value:
        - globals.set:
            id: max_cell_voltage
            value: !lambda return x;
    delta_cell_voltage:
      id: jkbms_delta_cell_voltage_internal
      internal: true
    cell_voltage_1:
      id: jkbms_cell_voltage_1_internal
      internal: true
    cell_voltage_2:
      id: jkbms_cell_voltage_2_internal
      internal: true
    cell_voltage_3:
      id: jkbms_cell_voltage_3_internal
      internal: true
    cell_voltage_4:
      id: jkbms_cell_voltage_4_internal
      internal: true
    cell_voltage_5:
      id: jkbms_cell_voltage_5_internal
      internal: true
    cell_voltage_6:
      id: jkbms_cell_voltage_6_internal
      internal: true
    cell_voltage_7:
      id: jkbms_cell_voltage_7_internal
      internal: true
    cell_voltage_8:
      id: jkbms_cell_voltage_8_internal
      internal: true
    state_of_charge:
      id: jkbms_soc_internal
      internal: true
      on_value:
        - globals.set:
            id: soc
            value: !lambda return x;
    mosfet_temperature:
      id: jkbms_mosfet_temp_internal
      internal: true
      on_value:
        - globals.set:
            id: mos_temp
            value: !lambda return x;
    battery_temperature:
      id: jkbms_battery_temp_internal
      internal: true
      on_value:
        - globals.set:
            id: cell_temp
            value: !lambda return x;
  - platform: template
    id: jkbms_voltage
    name: "JKBMS total voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_voltage_internal)->state;
  - platform: template
    id: jkbms_current
    name: "JKBMS current"
    unit_of_measurement: "A"
    accuracy_decimals: 1
    device_class: current
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_current_internal)->state;
  - platform: template
    id: jkbms_power
    name: "JKBMS power"
    unit_of_measurement: "W"
    accuracy_decimals: 1
    device_class: power
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_power_internal)->state;
  - platform: template
    id: jkbms_min_cell_voltage
    name: "JKBMS min cell voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_min_cell_voltage_internal)->state;
  - platform: template
    id: jkbms_max_cell_voltage
    name: "JKBMS max cell voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_max_cell_voltage_internal)->state;
  - platform: template
    id: jkbms_delta_cell_voltage
    name: "JKBMS delta cell voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_delta_cell_voltage)->state;
  - platform: template
    id: jkbms_cell_voltage_1
    name: "JKBMS cell voltage 1"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_1_internal)->state;
  - platform: template
    id: jkbms_cell_voltage_2
    name: "JKBMS cell voltage 2"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_2_internal)->state;
  - platform: template
    id: jkbms_cell_voltage_3
    name: "JKBMS cell voltage 3"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_3_internal)->state;
  - platform: template
    id: jkbms_cell_voltage_4
    name: "JKBMS cell voltage 4"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_4_internal)->state;
  - platform: template
    id: jkbms_cell_voltage_5
    name: "JKBMS cell voltage 5"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_5_internal)->state;
  - platform: template
    id: jkbms_cell_voltage_6
    name: "JKBMS cell voltage 6"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_6_internal)->state;
  - platform: template
    id: jkbms_cell_voltage_7
    name: "JKBMS cell voltage 7"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_7_internal)->state;
  - platform: template
    id: jkbms_cell_voltage_8
    name: "JKBMS cell voltage 8"
    unit_of_measurement: "V"
    accuracy_decimals: 3
    device_class: voltage
    state_class: measurement
    update_interval: 60s
    lambda: return (jkbms_cell_voltage_8_internal)->state;
  - platform: template
    id: jkbms_soc
    name: "JKBMS state of charge"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: return (jkbms_soc_internal)->state;
  - platform: template
    id: jkbms_mosfet_temp
    name: "JKBMS mosfet temperature"
    unit_of_measurement: "°C"
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 60s
    lambda: return (jkbms_mosfet_temp_internal)->state;
  - platform: template
    id: jkbms_battery_temp
    name: "JKBMS battery temperature"
    unit_of_measurement: "°C"
    state_class: measurement
    accuracy_decimals: 1
    update_interval: 60s
    lambda: return (jkbms_battery_temp_internal)->state;

text_sensor:
  - platform: template
    id: jkbms_alarms
    name: "JKBMS alarms"
    update_interval: never
    lambda: |-
      static const std::map<std::string, binary_sensor::BinarySensor*> alarm_sensors_map {
        { "JKBMS system warning", id(jkbms_system_warn) },
        { "JKBMS cell voltage undervoltage protection", id(jkbms_cell_uvp) },
        { "JKBMS cell voltage overvoltage protection", id(jkbms_cell_ovp) },
        { "JKBMS overcurrent protection", id(jkbms_ocp) },
        { "JKBMS mosfet overtemperature protection", id(jkbms_mos_otp) },
        { "JKBMS battery temperature protection", id(jkbms_batt_tp) },
        { "JKBMS short circuit protection", id(jkbms_scp) },
        { "JKBMS coprocessor communication error", id(jkbms_cocpu_comm_err) },
        { "JKBMS balancer wire resistance too high", id(jkbms_high_wire_res) },
        { "JKBMS cell count mismatch", id(jkbms_cell_cnt_mismatch) }
      };
      std::string values = "";
      for (auto const& item: alarm_sensors_map) {
        if (item.second->state) {
          values += item.first;
          values += ", ";
        }
      }
      if (values.length() >= 2) {
        values.erase(values.length() - 2);
      }
      return values;
