jk_modbus:
  - id: bms_modbus
    uart_id: bms_uart
    rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: bms_modbus
    update_interval: 5s

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "JKBMS balancing"
    balancing_switch:
      name: "JKBMS balancing switch"
      on_state:
        - script.execute:
            id: lvgl_update_switch_value
            name: balancing_sw
            value: !lambda return x;
    charging:
      name: "JKBMS charging"
    discharging:
      name: "JKBMS discharging"
    online_status:
      name: "JKBMS online status"
      on_state:
        then:
          - script.execute:
              id: lvgl_update_status_icon
              name: bms_connection
              is_on: !lambda return x;

sensor:
  - platform: jk_bms
    cell_voltage_1:
      name: "JKBMS cell voltage 1"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell1voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_2:
      name: "JKBMS cell voltage 2"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell2voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_3:
      name: "JKBMS cell voltage 3"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell3voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_4:
      name: "JKBMS cell voltage 4"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell4voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_5:
      name: "JKBMS cell voltage 5"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell5voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_6:
      name: "JKBMS cell voltage 6"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell6voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_7:
      name: "JKBMS cell voltage 7"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell7voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_8:
      name: "JKBMS cell voltage 8"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell8voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_9:
      name: "JKBMS cell voltage 9"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell9voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_10:
      name: "JKBMS cell voltage 10"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell10voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_11:
      name: "JKBMS cell voltage 11"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell11voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_12:
      name: "JKBMS cell voltage 12"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell12voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_13:
      name: "JKBMS cell voltage 13"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell13voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_14:
      name: "JKBMS cell voltage 14"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell14voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_15:
      name: "JKBMS cell voltage 15"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell15voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_16:
      name: "JKBMS cell voltage 16"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: cell16voltage
            value: !lambda return value_accuracy_to_string(x, 3);
    power_tube_temperature:
      name: "JKBMS power tube temperature"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: tmos
            value: !lambda return value_accuracy_to_string(x, 0);
    temperature_sensor_1:
      name: "JKBMS temperature sensor 1"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: t1
            value: !lambda return value_accuracy_to_string(x, 0);
    temperature_sensor_2:
      name: "JKBMS temperature sensor 2"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: t2
            value: !lambda return value_accuracy_to_string(x, 0);
    total_voltage:
      name: "JKBMS total voltage"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: voltage
            value: !lambda return value_accuracy_to_string(x, 2);
    current:
      name: "JKBMS current"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: current
            value: !lambda return value_accuracy_to_string(x, 0);
    power:
      name: "JKBMS power"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: power
            value: !lambda return value_accuracy_to_string(x, 0);
    capacity_remaining:
      name: "JKBMS capacity remaining"
      on_value:
        - script.execute:
            id: lvgl_update_soc
            soc: !lambda return x;
    capacity_remaining_derived:
      name: "JKBMS capacity remaining derived"
      on_value:
        - script.execute:
            id: lvgl_update_label_value
            name: capacity
            value: !lambda return value_accuracy_to_string(x, 0);
    min_cell_voltage:
      name: "JKBMS min cell voltage"
    max_cell_voltage:
      name: "JKBMS max cell voltage"
    min_voltage_cell:
      name: "JKBMS min voltage cell"
    max_voltage_cell:
      name: "JKBMS max voltage cell"
    delta_cell_voltage:
      name: "JKBMS delta cell voltage"
    average_cell_voltage:
      name: "JKBMS average cell voltage"
    charging_power:
      name: "JKBMS charging power"
    discharging_power:
      name: "JKBMS discharging power"
    charging_cycles:
      name: "JKBMS charging cycles"
    total_charging_cycle_capacity:
      name: "JKBMS total charging cycle capacity"
    current_calibration:
      name: "JKBMS current calibration"
    device_address:
      name: "JKBMS device address"
    sleep_wait_time:
      name: "JKBMS sleep wait time"
    alarm_low_volume:
      name: "JKBMS alarm low volume"
    manufacturing_date:
      name: "JKBMS manufacturing date"
    total_runtime:
      name: "JKBMS total runtime"
    actual_battery_capacity:
      name: "JKBMS actual battery capacity"

switch:
  - platform: jk_bms
    charging:
      name: "JKBMS charging"
      on_turn_on:
        - script.execute:
            id: lvgl_update_switch_value
            name: charging_sw
            value: true
      on_turn_off:
        - script.execute:
            id: lvgl_update_switch_value
            name: charging_sw
            value: false
    discharging:
      name: "JKBMS discharging"
      on_turn_on:
        - script.execute:
            id: lvgl_update_switch_value
            name: discharging_sw
            value: true
      on_turn_off:
        - script.execute:
            id: lvgl_update_switch_value
            name: discharging_sw
            value: false
    # balancer:
    #   name: "JKBMS balancing"
    #   on_turn_on:
    #     - script.execute:
    #         id: lvgl_update_switch_value
    #         name: 'balancing_sw'
    #         value: true
    #   on_turn_off:
    #     - script.execute:
    #         id: lvgl_update_switch_value
    #         name: 'balancing_sw'
    #         value: false

text_sensor:
  - platform: jk_bms
    errors:
      name: "JKBMS errors"
      on_value:
        - script.execute:
            id: lvgl_update_error_label
            error: !lambda return x;
    operation_mode:
      name: "JKBMS operation mode"
    battery_type:
      name: "JKBMS battery type"
    password:
      name: "JKBMS password"
    device_type:
      name: "JKBMS device type"
    software_version:
      name: "JKBMS software version"
    manufacturer:
      name: "JKBMS manufacturer"
    total_runtime_formatted:
      name: "JKBMS total runtime formatted"