jk_modbus:
  - id: bms_modbus
    uart_id: bms_uart
    rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: bms_modbus
    update_interval: 5s

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "JKBMS balancing"
    charging:
      name: "JKBMS charging"
    discharging:
      name: "JKBMS discharging"
    online_status:
      name: "JKBMS online status"
      on_press:
        - lvgl.widget.update:
            id: bms_connection
            text_color: '!lambda return x ? id(color_on) : id(color_off);'

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "JKBMS min cell voltage"
    max_cell_voltage:
      name: "JKBMS max cell voltage"
    min_voltage_cell:
      name: "JKBMS min voltage cell"
    max_voltage_cell:
      name: "JKBMS max voltage cell"
    delta_cell_voltage:
      name: "JKBMS delta cell voltage"
    average_cell_voltage:
      name: "JKBMS average cell voltage"
    cell_voltage_1:
      name: "JKBMS cell voltage 1"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell1voltage,
            value: x
    cell_voltage_2:
      name: "JKBMS cell voltage 2"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell2voltage, l_value: x }
    cell_voltage_3:
      name: "JKBMS cell voltage 3"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell3voltage, l_value: x }
    cell_voltage_4:
      name: "JKBMS cell voltage 4"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell4voltage, l_value: x }
    cell_voltage_5:
      name: "JKBMS cell voltage 5"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell5voltage, l_value: x }
    cell_voltage_6:
      name: "JKBMS cell voltage 6"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell6voltage, l_value: x }
    cell_voltage_7:
      name: "JKBMS cell voltage 7"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell7voltage, l_value: x }
    cell_voltage_8:
      name: "JKBMS cell voltage 8"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell8voltage, l_value: x }
    cell_voltage_9:
      name: "JKBMS cell voltage 9"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell9voltage, l_value: x }
    cell_voltage_10:
      name: "JKBMS cell voltage 10"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell10voltage, l_value: x }
    cell_voltage_11:
      name: "JKBMS cell voltage 11"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell11voltage, l_value: x }
    cell_voltage_12:
      name: "JKBMS cell voltage 12"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell12voltage, l_value: x }
    cell_voltage_13:
      name: "JKBMS cell voltage 13"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell13voltage, l_value: x }
    cell_voltage_14:
      name: "JKBMS cell voltage 14"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell14voltage, l_value: x }
    cell_voltage_15:
      name: "JKBMS cell voltage 15"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell15voltage, l_value: x }
    cell_voltage_16:
      name: "JKBMS cell voltage 16"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: cell16voltage, l_value: x }
    power_tube_temperature:
      name: "JKBMS power tube temperature"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: tmos, l_value: x }
    temperature_sensor_1:
      name: "JKBMS temperature sensor 1"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: t1, l_value: x }
    temperature_sensor_2:
      name: "JKBMS temperature sensor 2"
      on_value:
        - script.execute:
            id: lvgl_update_label
            name: t2, l_value: x }
    total_voltage:
      name: "JKBMS total voltage"
    current:
      name: "JKBMS current"
    power:
      name: "JKBMS power"
    charging_power:
      name: "JKBMS charging power"
    discharging_power:
      name: "JKBMS discharging power"
    capacity_remaining:
      name: "JKBMS capacity remaining"
    capacity_remaining_derived:
      name: "JKBMS capacity remaining derived"
    charging_cycles:
      name: "JKBMS charging cycles"
    total_charging_cycle_capacity:
      name: "JKBMS total charging cycle capacity"
    battery_strings:
      name: "JKBMS battery strings"
    total_battery_capacity_setting:
      name: "JKBMS total battery capacity setting"
    current_calibration:
      name: "JKBMS current calibration"
    device_address:
      name: "JKBMS device address"
    sleep_wait_time:
      name: "JKBMS sleep wait time"
    alarm_low_volume:
      name: "JKBMS alarm low volume"
    manufacturing_date:
      name: "JKBMS manufacturing date"
    total_runtime:
      name: "JKBMS total runtime"
    actual_battery_capacity:
      name: "JKBMS actual battery capacity"

switch:
  - platform: jk_bms
    charging:
      name: "JKBMS charging"
      on_turn_on:
      on_turn_off:
        - <<: !include { file: actions/update-switch-value.yaml, sw_name: charge, sw_value: x }
    discharging:
      name: "JKBMS discharging"
      on_turn_on:
      on_turn_off:
        - <<: !include { file: actions/update-switch-value.yaml, sw_name: disacharge, sw_value: x }
    balancer:
      name: "JKBMS balancing"
      on_turn_on:
      on_turn_off:
        - <<: !include { file: actions/update-switch-value.yaml, sw_name: balance, sw_value: x }
