jk_modbus:
  - id: bms_modbus
    uart_id: bms_uart
    rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: bms_modbus
    update_interval: 5s

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "JKBMS balancing"
    balancing_switch:
      name: "JKBMS balancing switch"
      on_state:
        - script.execute:
            id: lvgl_update_switch_value2
            sw: balance_sw
            value: !lambda return x;
    charging:
      name: "JKBMS charging"
    discharging:
      name: "JKBMS discharging"
    online_status:
      name: "JKBMS online status"
      on_state:
        then:
          - script.execute:
              id: lvgl_update_status_icon
              name: bms_connection
              is_on: !lambda return x;

sensor:
  - platform: jk_bms
    cell_voltage_1:
      name: "JKBMS cell voltage 1"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell1voltage_value_label
            unit_lbl: cell1voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_2:
      name: "JKBMS cell voltage 2"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell2voltage_value_label
            unit_lbl: cell2voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_3:
      name: "JKBMS cell voltage 3"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell3voltage_value_label
            unit_lbl: cell3voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_4:
      name: "JKBMS cell voltage 4"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell4voltage_value_label
            unit_lbl: cell4voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_5:
      name: "JKBMS cell voltage 5"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell5voltage_value_label
            unit_lbl: cell5voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_6:
      name: "JKBMS cell voltage 6"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell6voltage_value_label
            unit_lbl: cell6voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_7:
      name: "JKBMS cell voltage 7"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell7voltage_value_label
            unit_lbl: cell7voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_8:
      name: "JKBMS cell voltage 8"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell8voltage_value_label
            unit_lbl: cell8voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_9:
      name: "JKBMS cell voltage 9"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell9voltage_value_label
            unit_lbl: cell9voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_10:
      name: "JKBMS cell voltage 10"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell10voltage_value_label
            unit_lbl: cell10voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_11:
      name: "JKBMS cell voltage 11"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell11voltage_value_label
            unit_lbl: cell11voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_12:
      name: "JKBMS cell voltage 12"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell12voltage_value_label
            unit_lbl: cell12voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_13:
      name: "JKBMS cell voltage 13"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell13voltage_value_label
            unit_lbl: cell13voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_14:
      name: "JKBMS cell voltage 14"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell14voltage_value_label
            unit_lbl: cell14voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_15:
      name: "JKBMS cell voltage 15"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell15voltage_value_label
            unit_lbl: cell15voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    cell_voltage_16:
      name: "JKBMS cell voltage 16"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: cell16voltage_value_label
            unit_lbl: cell16voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 3);
    power_tube_temperature:
      name: "JKBMS power tube temperature"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: tmos_value_label
            unit_lbl: tmos_unit_label
            value: !lambda return value_accuracy_to_string(x, 0);
    temperature_sensor_1:
      name: "JKBMS temperature sensor 1"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: t1_value_label
            unit_lbl: t1_unit_label
            value: !lambda return value_accuracy_to_string(x, 0);
    temperature_sensor_2:
      name: "JKBMS temperature sensor 2"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: t2_value_label
            unit_lbl: t2_unit_label
            value: !lambda return value_accuracy_to_string(x, 0);
    total_voltage:
      name: "JKBMS total voltage"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: voltage_value_label
            unit_lbl: voltage_unit_label
            value: !lambda return value_accuracy_to_string(x, 2);
    current:
      name: "JKBMS current"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: current_value_label
            unit_lbl: current_unit_label
            value: !lambda return value_accuracy_to_string(x, 0);
    power:
      name: "JKBMS power"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: power_value_label
            unit_lbl: power_unit_label
            value: !lambda return value_accuracy_to_string(x, 0);
    capacity_remaining:
      name: "JKBMS capacity remaining"
      on_value:
        - script.execute:
            id: lvgl_update_soc
            soc: !lambda return x;
    capacity_remaining_derived:
      name: "JKBMS capacity remaining derived"
      on_value:
        - script.execute:
            id: lvgl_update_label_value2
            val_lbl: capacity_value_label
            unit_lbl: capacity_unit_label
            value: !lambda return value_accuracy_to_string(x, 0);
    min_cell_voltage:
      name: "JKBMS min cell voltage"
    max_cell_voltage:
      name: "JKBMS max cell voltage"
    min_voltage_cell:
      name: "JKBMS min voltage cell"
    max_voltage_cell:
      name: "JKBMS max voltage cell"
    delta_cell_voltage:
      name: "JKBMS delta cell voltage"
    average_cell_voltage:
      name: "JKBMS average cell voltage"
    charging_power:
      name: "JKBMS charging power"
    discharging_power:
      name: "JKBMS discharging power"
    charging_cycles:
      name: "JKBMS charging cycles"
    total_charging_cycle_capacity:
      name: "JKBMS total charging cycle capacity"
    current_calibration:
      name: "JKBMS current calibration"
    device_address:
      name: "JKBMS device address"
    sleep_wait_time:
      name: "JKBMS sleep wait time"
    alarm_low_volume:
      name: "JKBMS alarm low volume"
    manufacturing_date:
      name: "JKBMS manufacturing date"
    total_runtime:
      name: "JKBMS total runtime"
    actual_battery_capacity:
      name: "JKBMS actual battery capacity"

switch:
  - platform: jk_bms
    charging:
      name: "JKBMS charging"
      on_turn_on:
        - script.execute:
            id: lvgl_update_switch_value2
            sw: charge_sw
            value: true
      on_turn_off:
        - script.execute:
            id: lvgl_update_switch_value2
            sw: charge_sw
            value: false
    discharging:
      name: "JKBMS discharging"
      on_turn_on:
        - script.execute:
            id: lvgl_update_switch_value2
            sw: discharge_sw
            value: true
      on_turn_off:
        - script.execute:
            id: lvgl_update_switch_value2
            sw: discharge_sw
            value: false

text_sensor:
  - platform: jk_bms
    errors:
      name: "JKBMS errors"
      on_value:
        - script.execute:
            id: lvgl_update_error_label
            error: !lambda return x;
    operation_mode:
      name: "JKBMS operation mode"
    battery_type:
      name: "JKBMS battery type"
    password:
      name: "JKBMS password"
    device_type:
      name: "JKBMS device type"
    software_version:
      name: "JKBMS software version"
    manufacturer:
      name: "JKBMS manufacturer"
    total_runtime_formatted:
      name: "JKBMS total runtime formatted"